Repository openshift/cluster-version-operator, pull requests merged in 2018-12, with the labels that each got.

#60 install: drop cvoconfig
  install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
Labels: approved, lgtm, size/S

#66 manifest: show the Failing condition in a column
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Labels: approved, lgtm, size/XS

#68 Requeue clusteroperator on NotFound
  lib/resourcebuilder/errors.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/sync.go
  pkg/cvo/sync_test.go
Labels: approved, lgtm, size/M

#65 docs/dev/operators: Document ComponentOverride injection
  docs/dev/clusterversion.md
Labels: approved, lgtm, size/M

#71 api: Remove operatorstatus object before 4.0
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Labels: approved, lgtm, size/S

#72 docs: Capture how to write messages for cluster operator conditions
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/S
