Repository openshift/cluster-version-operator, pull requests merged in 2018-09, with the labels that each got.

#14 Update CVO to flat updatepayload structure
  Dockerfile
  Gopkg.lock
  hack/build-image.sh
  install/00_clusterversionoperator_00_namespace.yaml
  install/00_clusterversionoperator_01_cvoconfig.crd.yaml
  install/00_clusterversionoperator_02_roles.yaml
  install/00_clusterversionoperator_03_scc.yaml
  install/00_clusterversionoperator_04_deployment.yaml
  lib/manifest.go
  lib/manifest_test.go
  lib/resourceapply/core.go
  lib/resourceapply/rbac.go
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcebuilder/core.go
  lib/resourcebuilder/interface.go
  lib/resourcebuilder/rbac.go
  lib/resourcebuilder/register.go
  lib/resourcemerge/cv.go
  lib/resourcemerge/os.go
  lib/resourcemerge/rbac.go
  lib/resourceread/core.go
  lib/resourceread/rbac.go
  pkg/cvo/cvo.go
  pkg/cvo/os.go
  pkg/cvo/status.go
  pkg/cvo/sync.go
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/XXL

#15 Add `image <short-name>` command to return image from updatepayload
  Gopkg.lock
  Gopkg.toml
  cmd/image.go
  lib/resourceread/image.go
  pkg/cvo/cvo.go
  pkg/cvo/image.go
  pkg/cvo/updatepayload.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/image/docker10/doc.go
  vendor/github.com/openshift/api/image/docker10/dockertypes.go
  vendor/github.com/openshift/api/image/docker10/register.go
  vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/doc.go
  vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  vendor/github.com/openshift/api/image/dockerpre012/register.go
  vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/doc.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/legacy.go
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#16 Add render subcommand for CVO
  cmd/main.go
  cmd/render.go
  cmd/start.go
  install/00_clusterversionoperator_04_deployment.yaml
  lib/resourcebuilder/interface.go
  pkg/cvo/cvo.go
  pkg/cvo/image.go
  pkg/cvo/render.go
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/L

#17 fix: go tmpl execute before parsing to Manifest
  lib/manifest.go
  lib/manifest_test.go
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/M

#19 fix: default location for update-payload from ci
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/XS

#20 add README.md
  README.md
  hack/push-image.sh
Labels: approved, lgtm, size/M

#21 manifests: Put CVO into the global order space (prefix 0000_)
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_01_cvoconfig.crd.yaml
  install/0000_00_cluster-version-operator_02_roles.yaml
  install/0000_00_cluster-version-operator_03_scc.yaml
  install/0000_00_cluster-version-operator_04_deployment.yaml
Labels: approved, lgtm, size/XS

#24 fixes CVO dependency on openshift-apiserver
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_00_cluster-version-operator_03_scc.yaml
Labels: approved, lgtm, size/M
