Repository openshift/cluster-version-operator, pull requests merged in 2018-10, with the labels that each got.

#28 dynamicclient: reset restmapper cache and try again on nomatch error
  pkg/cvo/internal/dynamicclient/client.go
Labels: approved, lgtm, size/S

#29 Drop CVO from release manifests
  Dockerfile
  pkg/cvo/render.go
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/L

#34 docs/dev: Second level operator FAQ
  docs/dev/operators.md
Labels: approved, lgtm, size/L

#37 approvers: update OWNERS to promote wking and abhinavdahiya to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#33 genric_handler: error when object has no name
  pkg/cvo/internal/generic.go
Labels: approved, lgtm, size/XS

#35 switch workload resource to daemonset
  install/0000_00_cluster-version-operator_03_daemonset.yaml
Labels: approved, lgtm, size/XS

#31 make operator status more kube-like
  cmd/start.go
  install/0000_00_cluster-version-operator_01_cvoconfig.crd.yaml
  lib/resourceapply/cv.go
  lib/resourcemerge/os.go
  pkg/apis/operatorstatus.openshift.io/v1/register.go
  pkg/apis/operatorstatus.openshift.io/v1/types.go
  pkg/apis/operatorstatus.openshift.io/v1/zz_generated.deepcopy.go
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/status.go
  pkg/cvo/sync.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/clusteroperator.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/fake/fake_clusteroperator.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/fake/fake_operatorstatus.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/fake/fake_operatorstatus.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/operatorstatus.go
  pkg/generated/clientset/versioned/typed/operatorstatus.openshift.io/v1/operatorstatus.openshift.io_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/operatorstatus.openshift.io/v1/clusteroperator.go
  pkg/generated/informers/externalversions/operatorstatus.openshift.io/v1/interface.go
  pkg/generated/listers/operatorstatus.openshift.io/v1/clusteroperator.go
  pkg/generated/listers/operatorstatus.openshift.io/v1/expansion_generated.go
  pkg/generated/listers/operatorstatus.openshift.io/v1/operatorstatus.go
Labels: approved, lgtm, size/XXL

#41 docs: add docs for ClusterOperator for operators
  docs/dev/clusteroperator.md
  docs/dev/operators.md
Labels: approved, lgtm, size/M

#42 docs: add checkpointer operator run level
  docs/dev/operators.md
Labels: approved, lgtm, size/XS
