Repository openshift/cluster-version-operator, pull requests merged in 2018-11, with the labels that each got.

#46 api: Add stub ClusterVersion CRD so that installer can reference it
  install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
Labels: approved, lgtm, size/M

#47 cvo: Report errors to conditions more consistently
  Gopkg.lock
  docs/dev/metrics.md
  lib/resourceapply/cv.go
  lib/resourcemerge/os.go
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/internal/dynamicclient/client.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status.go
  pkg/cvo/sync.go
  pkg/cvo/updatepayload.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, lgtm, size/XXL

#49 manifests: Add a service for CVO so that a ServiceMonitor can scrape it
  install/0001_00_cluster-version-operator_03_service.yaml
Labels: approved, lgtm, size/S

#38 Revert "switch workload resource to daemonset"
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#52 OWNERS: Yifan has moved on to other things :(
  OWNERS
Labels: approved, lgtm, size/XS

#54 metrics: Move default metrics port to 9101 in the open internal range
  cmd/start.go
  install/0001_00_cluster-version-operator_03_service.yaml
Labels: approved, lgtm, size/XS

#56 metrics: Default metrics port conflicts with node-exporter
  cmd/start.go
  install/0001_00_cluster-version-operator_03_service.yaml
Labels: approved, lgtm, size/S
