Repository openshift/cluster-version-operator, pull requests merged in 2018-08, with the labels that each got.

#2 *: read runtime parameters from CVOConfig
  cmd/main.go
  hack/update-codegen.sh
  pkg/apis/clusterversion.openshift.io/v1/cvoconfig.go
  pkg/apis/clusterversion.openshift.io/v1/doc.go
  pkg/apis/clusterversion.openshift.io/v1/register.go
  pkg/apis/clusterversion.openshift.io/v1/types.go
  pkg/apis/clusterversion.openshift.io/v1/url.go
  pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
  pkg/cincinnati/cincinnati.go
  pkg/cvo/cvo.go
  pkg/cvo/operator_status.go
  pkg/cvo/update.go
  pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/clusterversion.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/cvoconfig.go
  pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/fake/fake_clusterversion.openshift.io_client.go
  pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/fake/fake_cvoconfig.go
  pkg/generated/clientset/versioned/typed/clusterversion.openshift.io/v1/generated_expansion.go
  pkg/generated/informers/externalversions/clusterversion.openshift.io/v1/cvoconfig.go
  pkg/generated/informers/externalversions/clusterversion.openshift.io/v1/interface.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/clusterversion.openshift.io/v1/cvoconfig.go
  pkg/generated/listers/clusterversion.openshift.io/v1/expansion_generated.go
  pkg/version/version.go
Labels: size/XL

#3 *: fix a few issues
  cmd/main.go
  pkg/apis/clusterversion.openshift.io/v1/url.go
  pkg/cvo/update.go
Labels: size/S

#4 cvo: report entire update in status
  pkg/apis/clusterversion.openshift.io/v1/types.go
  pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
  pkg/cincinnati/cincinnati.go
  pkg/cvo/update.go
Labels: size/M

#5 cvo: properly update OperatorStatus
  pkg/cvo/update.go
Labels: size/XS

#6 cvo: add ability to apply updates
  Gopkg.lock
  Gopkg.toml
  pkg/apis/clusterversion.openshift.io/v1/types.go
  pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
  pkg/cvo/cvo.go
  pkg/cvo/update.go
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/pointer/pointer.go
Labels: size/L

#8 Add a Dockerfile
  Dockerfile
Labels: lgtm, size/XS

#9 *: add OWNERS file
  OWNERS
Labels: lgtm, size/XS

#10 Add CVO sync from payload
  Gopkg.lock
  cmd/start.go
  lib/manifest.go
  lib/manifest_test.go
  lib/resourceapply/batch.go
  lib/resourceapply/core.go
  lib/resourceapply/rbac.go
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcebuilder/core.go
  lib/resourcebuilder/interface.go
  lib/resourcebuilder/rbac.go
  lib/resourcemerge/batch.go
  lib/resourcemerge/core.go
  lib/resourcemerge/cv.go
  lib/resourcemerge/rbac.go
  lib/resourceread/apiext.go
  lib/resourceread/apps.go
  lib/resourceread/batch.go
  lib/resourceread/core.go
  lib/resourceread/rbac.go
  pkg/cvo/cvo.go
  pkg/cvo/sync.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
Labels: approved, lgtm, size/XXL

#11 Add: autoupdate controller
  cmd/start.go
  pkg/autoupdate/autoupdate.go
  pkg/autoupdate/autoupdate_test.go
Labels: approved, lgtm, size/L
