Repository openshift/cluster-version-operator, pull requests merged in 2019-02, with the labels that each got.

#107 metrics: Report a gauge for when cluster operator conditions change
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/L

#106 status: Report a percentage when performing the initial sync
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
Labels: approved, lgtm, size/S

#108 metrics: Fix flaky unit test from transition
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/S

#111 test: Fix flake when retrieving payloads
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/L

#88 Parallelize the payload execution
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
  pkg/start/start.go
Labels: approved, lgtm, size/XXL

#110 sync: Report a specific cluster operator error when not available
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/status.go
  pkg/payload/task.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/M

#114 cininnati: fix unknown version fetch
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm, size/L

#115 lib: ensureClusterOperatorStatus tracks RelatedObjects
  lib/resourcemerge/os.go
Labels: approved, lgtm, size/XS

#116 docs: Update CVO doc for run level and parallelization
  docs/dev/operators.md
Labels: approved, lgtm, size/M

#100 docs/dev/operators: Reorder assigned runlevels (machine API to 30, etc.)
  docs/dev/operators.md
Labels: approved, lgtm, size/S

#113 pkg/cincinnati: update unamrshal to node to match the result from cincinnati
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm, size/M

#117 hack: change override env for version
  hack/build-go.sh
  hack/build-image.sh
  hack/push-image.sh
Labels: approved, lgtm, size/S

#105 wait for COs versions to be correct
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
Labels: approved, lgtm, size/XL

#121 pkg/cincinnati: add required parameters to requests
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/L

#124 pkg/cvo: report actual metrics on Complete()
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, size/XS
