Repository openshift/cluster-version-operator, pull requests merged in 2019-07, with the labels that each got.

#214 install: add service monitor manifest
  install/0000_90_cluster-version-operator_00_servicemonitor.yaml
Labels: approved, lgtm, size/S

#220 Update openshift client-go and api
  Gopkg.lock
  pkg/cvo/cvo_test.go
  pkg/start/start_integration_test.go
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/consts.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
Labels: approved, lgtm, size/XXL

#221 payload/render: update the bootstrap render to skip servicemonitor
  pkg/payload/render.go
Labels: approved, lgtm, size/XS

#219 Add http transport for cincinnati to enable proxy
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/start/start.go
Labels: approved, lgtm, size/L

#222 document CVO behavior w/ respect to cluster operator conditions
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/S

#225 manifests: Update the CRD definitions with more accurate docs
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
Labels: approved, lgtm, size/XL

#224 inject proxy env vars into requesting workload resources
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/podspec.go
  lib/resourcebuilder/podspec_test.go
Labels: approved, lgtm, size/L

#226 Add certificate option to cincinnati client
  Gopkg.lock
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/internal/constants.go
  pkg/start/start.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL
