Repository openshift/cluster-version-operator, pull requests merged in 2019-05, with the labels that each got.

#183 Bug 1706202: Use klog directly or no line info is printed
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  pkg/autoupdate/autoupdate.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/cvo/updatepayload.go
  pkg/payload/payload.go
  pkg/payload/task_graph.go
  pkg/start/start.go
  pkg/verify/verify.go
Labels: approved, lgtm, size/L

#182 Fix tolerations
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/S

#181 Update version-patch.yaml in clusterversion.md
  docs/dev/clusterversion.md
Labels: approved, lgtm, size/M

#189 ClusterVersion version column should be last completed
  install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
Labels: approved, lgtm, size/XS

#190 status: Simplify operator not available status
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
Labels: approved, lgtm, size/M

#191 conditions: Use a consistent constant for the Failing condition
  docs/dev/metrics.md
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/L

#188 README: Fix "manfiests" -> "manifests" typo
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#192 status: Hide generic operator status in favor of more specific errors
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, size/M

#187 Bug 1702582: Log DeploymentConditions reason and message when Deployment is failing
  lib/resourcebuilder/apps.go
Labels: approved, lgtm, size/S

#186 Bug 1665011: updatepayload: prune older jobs to maintain limit.
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/M
