Repository openshift/cluster-version-operator, pull requests merged in 2019-06, with the labels that each got.

#196 pkg/verify: Test an armored, multi-key keyring
  pkg/verify/testdata/keyrings/combined.txt
  pkg/verify/verify_test.go
Labels: approved, lgtm, size/M

#197 Bug 1717619: metrics: Report reason as a label on the conditions metric
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/S

#199 lib/resourcemerge/core: Fix setInt32Ptr for "both nil" case
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, lgtm, size/M

#202 Bug 1717619: metrics: Report reason as a label on the conditions metric
  docs/dev/metrics.md
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/start/start_integration_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#203 metrics: Omit `cluster_version{type="completed"}` when not available
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/M

#198 Update Replica count too while ensuring deployment
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
Labels: approved, lgtm, size/M

#204 metrics: Give all cluster_version types a `from_version` label
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/L

#207 pkg/cvo: Standardize "%d/%d" -> "%d of %d"
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, size/XS

#178 Bug 1710172: lib/resourcemerge: Remove containers from existing based on required
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: 4.2, approved, bugzilla/valid-bug, lgtm, size/L

#212 Bug 1723945: Add a metric that combines the current age of the cluster with the current version
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#216 Fix remove containers logic
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, lgtm, size/S
