Repository openshift/cluster-version-operator, pull requests merged in 2019-03, with the labels that each got.

#125 clusteroperator: Skip waiting for progressing when versions expected
  pkg/cvo/internal/operatorstatus.go
Labels: approved, lgtm, size/XS

#126 install: fix column rendering for clusteroperator version
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Labels: approved, lgtm, size/XS

#127 manifests: operator should have cluster-critical-priority
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#129 manifest: switch pull policy to ifnotpresent
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#128 lib/resourcebuilder: update interface to include context when doing work
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apireg.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcebuilder/core.go
  lib/resourcebuilder/interface.go
  lib/resourcebuilder/rbac.go
  lib/resourcebuilder/security.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/generic.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/task.go
Labels: approved, lgtm, size/L

#134 sync: Double max parallelism of sync worker
  pkg/cvo/cvo.go
Labels: approved, lgtm, size/XS

#132 sync: Serve cluster operator gets from the cache lister
  pkg/cvo/cvo.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/sync_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/M

#133 sync: Distinguish between reconcile, initial, and sync states
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apireg.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcebuilder/core.go
  lib/resourcebuilder/interface.go
  lib/resourcebuilder/rbac.go
  lib/resourcebuilder/security.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/generic.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/task.go
Labels: approved, lgtm, size/L

#136 sync: Completely parallelize the initial payload
  pkg/cvo/cvo.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file.json
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file.yaml
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file.yml
  pkg/payload/payload_test.go
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/L

#137 Update ClusterOperator docs for changes to versions and cluster-scoped
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/M

#139 bump(k8s.io/apiexensions-apiserver): protobuf fixes
  Gopkg.lock
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
Labels: approved, lgtm, size/L

#140 Bug 1670727: install/0000_00_cluster-version-operator_03_deployment: Set 'strategy: Recreate'
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#143 test: Avoid collisions on namespace and lengthen shutdown timeout
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/XS

#141 Bug 1691513: CVO should retry initialization until cancelled to avoid wedging because of failing dependencies
  Makefile
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcebuilder/interface.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/updatepayload.go
  pkg/payload/task.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/L

#144 leaderelect: Prevent double close channel panic when shutting down lease
  pkg/start/start.go
Labels: approved, lgtm, size/XS

#149 BUG 1693051: install: drop deprecated crd
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Labels: approved, lgtm, size/M

#146 status: Correctly increment history and don't overwrite controller cache objects
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
Labels: approved, lgtm, size/L

#147 Remove hardcoded 'amd64' from Dockerfile to support multi-arch builds.
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS
