Repository openshift/cluster-version-operator, pull requests merged in 2019-12, with the labels that each got.

#272 Bug 1769717: Add support to EnsureServicePorts
  lib/resourceapply/core.go
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#276 Bug 1781283: Set resource requests on the extract job
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, size/XS

#278 Bug 1781284: Set resource requests on the extract job
  pkg/cvo/updatepayload.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#271 Bug 1775836: Add proxy support for CVO
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#241 pkg/payload/image: avoid rendering manifests
  pkg/payload/image.go
  pkg/payload/payload.go
Labels: approved, lgtm, size/M
