Repository openshift/cluster-version-operator, pull requests merged in 2019-08, with the labels that each got.

#231 pkg: switch to openshift-config for proxy CA
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/internal/constants.go
  pkg/start/start.go
Labels: approved, lgtm, size/M

#228 cincinnati: add arch parameter to requests
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/M

#234 Bug 1738527: install: add role bindings for prometheus service account
  install/0000_90_cluster-version-operator_00_prometheusrole.yaml
  install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/payload/render.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#235 Bug 1738527: install: enable prometheus-operator to watch over namespace in search for ServiceMonitor
  install/0000_00_cluster-version-operator_00_namespace.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#236 Bug 1741645: pkg/cvo/metrics: Report cluster-version conditions with reasons
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#233 Bug 1739988: Stop double reporting "failure" cluster_version
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#238 Bug 1741786: pkg/cvo: Drop ClusterVersion defaulting during bootstrap
  bootstrap/bootstrap-pod.yaml
  cmd/start.go
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#240 Bug 1726455: Reconcile container ResourceRequirements in resource merge
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#232 Bug 1717632: install: add alerts for cluster-version-operator
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#244 pkg/cvo: ensure payload is retirved once when forced upgrade
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, size/L
