Repository openshift/cluster-version-operator, pull requests merged in 2019-04, with the labels that each got.

#151 cvo: fix max_workers to number of nodes in graph
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, size/XS

#155 Bug 1670727: install/0000_00_cluster-version-operator_03_deployment: Fix Recreate strategy
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#156 metrics: Report when the CVO is transitioning a payload
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/M

#153 SetOperatorStatusCondition update transition time for existing
  lib/resourcemerge/os.go
Labels: approved, lgtm, size/XS

#157 docs/dev/clusteroperator: Fix "it's" -> "its" typo
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/XS

#159 resource-apply: add release.openshift.io/create-only annotation
  lib/resourceapply/apiext.go
  lib/resourceapply/apireg.go
  lib/resourceapply/apps.go
  lib/resourceapply/batch.go
  lib/resourceapply/core.go
  lib/resourceapply/cv.go
  lib/resourceapply/interface.go
  lib/resourceapply/rbac.go
  lib/resourceapply/security.go
  pkg/cvo/internal/generic.go
  pkg/cvo/internal/generic_test.go
Labels: approved, lgtm, size/L

#160 doc: explain the create-only annotation to developers
  docs/dev/operators.md
Labels: approved, lgtm, size/XS

#158 status: Report the operators that have not yet deployed
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
  pkg/cvo/testdata/paralleltest/manifests/.gitkeep
  pkg/cvo/testdata/paralleltest/release-manifests/0000_10_a_file.yaml
  pkg/cvo/testdata/paralleltest/release-manifests/0000_20_a_file.yaml
  pkg/cvo/testdata/paralleltest/release-manifests/0000_20_b_file.yaml
  pkg/cvo/testdata/paralleltest/release-manifests/image-references
  pkg/cvo/testdata/paralleltest/release-manifests/release-metadata
  pkg/payload/task.go
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, size/XL

#161 docs: degraded condition
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/M

#166 sync: During reconcile, try different parts of the payload and don't hang
  pkg/cvo/sync_worker.go
  pkg/payload/task_graph.go
Labels: approved, lgtm, size/M

#150 Ensure channel isn't empty on update check
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm, size/M

#172 Bug 1702087: install/0000_00_cluster-version-operator_01_clusteroperator.crd: Failing -> Degraded
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Labels: approved, lgtm, size/XS

#169 start: Initialize the payload and fail if it can't be read at startup
  pkg/cvo/cvo.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/M

#162 pkg/cincinnati: Soften unknown-version message
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
Labels: approved, lgtm, size/XS

#175 test: Fix flake in RunGraph, comparing the wrong list (errs vs messages)
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, size/XS

#176 BUG 1703158 cvo: update the status reporter to preserve the previous Generation
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
Labels: approved, lgtm, size/M

#177 Preserve up to 50 version history entries
  pkg/cvo/status.go
Labels: approved, lgtm, size/XS

#174 Add node-selector annotation to namespace
  install/0000_00_cluster-version-operator_00_namespace.yaml
Labels: approved, lgtm, size/XS

#173 docs: Describe upgrade ordering and design
  docs/dev/operators.md
  docs/dev/upgrades.md
Labels: approved, size/M

#179 cvo: Verified true boolean not written to cv.status.history during update
  pkg/cvo/cvo.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/M

#180 test: Tolerate when sync reports partial status "Working towards"
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/S
