Repository openshift/cluster-version-operator, pull requests merged in 2019-01, with the labels that each got.

#73 docs: update status explanation
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/S

#63 cvo: Record history of changes to version and report target version
  Gopkg.lock
  install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  lib/validation/validation.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/updatepayload.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#74 docs: cluster-config-operator needs runlevel
  docs/dev/operators.md
Labels: approved, lgtm, size/XS

#81 *: update default upstream URL
  docs/dev/metrics.md
  pkg/cvo/cvo.go
Labels: approved, lgtm, size/XS

#80 Revert "clusteroperator: return RetryLaterError on not found"
  pkg/cvo/internal/operatorstatus.go
Labels: approved, lgtm, size/S

#84 pkg/cincinnati: fix media-type
  pkg/cincinnati/cincinnati.go
Labels: approved, lgtm, size/XS

#82 sync: Do config syncing in the background
  Gopkg.lock
  README.md
  cmd/start.go
  hack/test-integration.sh
  hack/test-prerequisites.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_integration_test.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/internal/generic.go
  pkg/cvo/status.go
  pkg/cvo/sync.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
  pkg/cvo/updatepayload.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
Labels: approved, lgtm, size/XXL

#86 set cpu request for operator
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, size/XS

#87 cvo: Release our leader lease when we are gracefully terminated
  cmd/main.go
  cmd/render.go
  cmd/start.go
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync.go
  pkg/cvo/sync_test.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/XXL

#91 test: hack/test-prerequisites.go was seeing a few flakes, retry differently
  hack/test-prerequisites.go
Labels: approved, lgtm, size/XS

#90 Increase the QPS limits on clients slightly and use protobuf for sync
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcebuilder/core.go
  lib/resourcebuilder/helper.go
  lib/resourcebuilder/rbac.go
  lib/resourcebuilder/security.go
  pkg/cvo/cvo.go
  pkg/start/start.go
Labels: approved, lgtm, size/M

#89 cvo: Don't wake the CVO on a cluster operator change
  pkg/cvo/cvo.go
Labels: approved, lgtm, size/XS

#93 docs: Add obligation to create ClusterOperator
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/XS

#95 make it clear that everyone needs a clusteroperator
  docs/dev/clusteroperator.md
Labels: approved, lgtm, size/XS

#94 add 'co' as shortname for clusteroperators
  install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Labels: approved, lgtm, size/XS

#92 metrics: Report the age of the current payload for alerting
  docs/dev/metrics.md
  pkg/cvo/cvo.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, size/L

#103 metrics: Report cluster_version as seconds since the epoch per type
  docs/dev/metrics.md
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm, size/L

#97 refactor: Extract payload related functions for clarity
  cmd/image.go
  cmd/render.go
  lib/manifest.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status.go
  pkg/cvo/sync.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/updatepayload.go
  pkg/payload/image.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/render.go
  pkg/payload/task.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/XXL

#102 status: Generation should be set by what the sync worker is doing
  Gopkg.lock
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/start/start_integration_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L
