Repository openshift/cluster-version-operator, pull requests merged in 2019-10, with the labels that each got.

#247 Bug 1756461: pkg/cvo/status: Don't clobber last.CompletionTime when adding new entries
  pkg/cvo/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#246 docs/dev/clusterversion: Set 'group' in patch manifests
  docs/dev/clusterversion.md
Labels: approved, lgtm, size/XS

#254 Bug 1665828: cmd/main.go: fix cli use to cluster-version-operator instead of version
  cmd/main.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#256 bug 1764017: Fix replicas comparison
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#255 Bug 1763821: pkg/payload/task_graph: Canceling the task graph partway though is an error even if no tasks fail
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#259 Bug 1755383: Add v1 CRD support and stop hotlooping
  lib/resourceapply/apiext.go
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/register.go
  lib/resourcemerge/apiext.go
  lib/resourceread/apiext.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#265 apiext: wait for CRD using v1beta1 for compatibility on upgrades
  lib/resourcebuilder/apiext.go
Labels: approved, lgtm, size/XS

#243 Bug 1730401: prevent automatic upgrades for clusters with cluster operators reporting Upgradeable false
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/upgradeable.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/precondition.go
  pkg/payload/precondition/precondition_test.go
  pkg/payload/task.go
  pkg/start/start_integration_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#223 Adding support for other archs than amd64
  Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS
