Repository openshift/cluster-version-operator, pull requests merged in 2019-11, with the labels that each got.

#268 Bug 1685338: pkg/cvo: Reason granularity for RemoteFailed
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#252 Allow excluding manifests from CVO payload
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, size/M

#269 Add annotations to manifests to exclude in hosted deployment
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  install/0001_00_cluster-version-operator_03_service.yaml
Labels: approved, lgtm, size/S

#261 Bug 1762920: install: add alerts for cluster-version-operator
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/payload/render.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#267 Bug 1766907: Add proxy support for CVO.
  README.md
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#201 docs/user/reconciliation: Document release-image application
  docs/user/reconciliation.md
  docs/user/tasks-by-number-and-component.svg
  docs/user/tasks-flatten-by-number-and-component.svg
  hack/cluster-version-util/main.go
  hack/cluster-version-util/task_graph.go
  pkg/payload/task_graph.go
Labels: approved, lgtm, size/XXL
