Repository openshift/cluster-version-operator, pull requests merged in 2020-10, with the labels that each got.

#461 Bug 1884209: Moving the go version to 1.15 as the Dockerfile.rhel already on it
  Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#464 Bug 1884334: pkv/cvo/status: Raise Operator leveling grace-period to 40 minutes
  docs/user/status.md
  pkg/cvo/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#462 Bug 1883705: *: Move to klog v2
  cmd/image.go
  cmd/main.go
  cmd/render.go
  cmd/start.go
  go.mod
  lib/manifest_test.go
  lib/resourceapply/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
  lib/resourcemerge/meta_test.go
  pkg/autoupdate/autoupdate.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/cvo/updatepayload.go
  pkg/cvo/upgradeable.go
  pkg/payload/payload.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/precondition.go
  pkg/payload/task_graph.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
  pkg/verify/configmap.go
  pkg/verify/persist.go
  pkg/verify/store/configmap/configmap.go
  pkg/verify/store/sigstore/sigstore.go
  pkg/verify/verify.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#454 Fixing spelling of notUpradeableCondition
  pkg/cvo/upgradeable.go
Labels: approved, lgtm

#447 docs: update cluster_installer description
  docs/dev/metrics.md
  pkg/cvo/metrics.go
Labels: approved, lgtm

#466 Fix typo in goarch variable
  hack/build-go.sh
Labels: approved, lgtm

#446 Bug 1872906: pkg/start: Release leader lease on graceful shutdown
  bootstrap/bootstrap-pod.yaml
  cmd/start.go
  install/0000_00_cluster-version-operator_03_deployment.yaml
  lib/resourceread/apiext_test.go
  pkg/autoupdate/autoupdate.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/egress.go
  pkg/cvo/metrics.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#468 Updating cluster-version-operator builder & base images to be consistent with ART
  Dockerfile.rhel
Labels: approved, lgtm

#469 Bug 1886900: pkg/cvo/sync_worker: Drop "Manifest: ..." logging
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#472 Bug 1886900: pkg/cvo/sync_worker: Demote "Status change: ..." logging to v6
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#474 Fixing go doc for equalUpdate()
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#475 hack/log-explainer: Don't crash if run on truncated logs
  hack/log-explainer.py
Labels: approved, lgtm

#477 Bug 1891143: pkg/cvo/metrics: Abandon child goroutines after shutdownContext expires
  pkg/cvo/metrics.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#478 Doc fix for cluster operator creation step
  docs/dev/clusteroperator.md
Labels: approved, lgtm
