Repository openshift/cluster-version-operator, pull requests merged in 2020-06, with the labels that each got.

#355 pkg/cvo/status: Fix "syncDegradedStatus" -> "syncFailingStatus" comment
  pkg/cvo/status.go
Labels: approved, lgtm

#377 pkg/payload/task_graph: "on" -> "on worker" logging
  pkg/payload/task_graph.go
Labels: approved, lgtm

#373 pkg/cvo/sync_worker: Promote "Sync succeeded" to v4
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#374 pkg/cvo/sync_worker: Flatten a nested 'if changed'
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#368 pkg/cvo/availableupdates: Split 'At' into LastAttempt and LastSyncOrConfigChange
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm

#375 pkg/cvo/sync_worker: Drop unused 'reconciling' from SyncWorker
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#372 Bug 1838497: pkg/cvo/sync_worker: Do not treat "All errors were context errors..." as success
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#359 Do not build with CGO_ENABLED=0
  hack/build-go.sh
Labels: approved, lgtm

#379 Bug 1843732: pkg/cvo/sync_worker: Do not treat "All errors were context errors..." as success
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#264 pkg/payload/task_graph: Handle node pushing and result collection without a goroutine
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, size/L

#371 pkg/cvo: Set NoDesiredImage reason when desired.Image is empty
  docs/user/reconciliation.md
  docs/user/status.md
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
Labels: approved, lgtm

#387 CONTRIBUTING: Add a contributing file
  CONTRIBUTING.md
  README.md
  lib/resourceread/apiext_test.go
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm

#357 Extend CVO alerts to cover update retrieval
  docs/user/status.md
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics.go
Labels: approved, lgtm

#383 Bug 1847672: Expand supported set of probe field mutations
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#385 Bug 1809195: Remove '-' from servicemonitor spec
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#354 Bug 1826349: hack/build-go: Use OS_GIT_VERSION if available
  hack/build-go.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#393 Bug 1840343: pkg/verify: Parallelize HTTP(S) signature retrieval
  pkg/cvo/cvo.go
  pkg/verify/configmap.go
  pkg/verify/store/configmap/configmap.go
  pkg/verify/store/memory/memory.go
  pkg/verify/store/parallel/parallel.go
  pkg/verify/store/parallel/parallel_test.go
  pkg/verify/store/serial/serial.go
  pkg/verify/store/serial/serial_test.go
  pkg/verify/store/store.go
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#294 pkg/verify: Refactor signature fetching to only use a Store interface
  pkg/cvo/cvo.go
  pkg/verify/configmap.go
  pkg/verify/store/configmap/configmap.go
  pkg/verify/store/memory/memory.go
  pkg/verify/store/serial/serial.go
  pkg/verify/store/serial/serial_test.go
  pkg/verify/store/store.go
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, size/L

#384 Add an alert to CVO that fires when cluster is not upgradeable
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm
