Repository openshift/cluster-version-operator, pull requests merged in 2020-09, with the labels that each got.

#450 Update clusterversion.md
  docs/dev/clusterversion.md
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test

#451 Bug 1873900: pkg/cvo/sync_worker: Grow logging in SyncWorker.Update
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#376 Bug 1841239: Avoid pre-creating clusteroperators that should be excluded
  hack/cluster-version-util/task_graph.go
  lib/resourcebuilder/interface.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/sync_worker.go
  pkg/cvo/testdata/payloadtest/release-manifests/0000_20_a_exclude.yml
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/task_graph_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#457 Bug 1878163: Dockerfile.rhel: Bump to Go 1.15
  Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#455 Bug 1873900: pkg/payload/task_graph: Avoid deadlocking on cancel with workCh queue
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#452 Bug 1880285: hack/log-explainer: Render CVO logs for easier analysis
  hack/log-explainer.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
