Repository openshift/cluster-version-operator, pull requests merged in 2020-01, with the labels that each got.

#290 Bug 1787334: pkg/cvo/updatepayload: Drop ephemeral-storage request
  pkg/cvo/updatepayload.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#288 Bug 1786315: pkg/cvo/updatepayload: Drop ephemeral-storage request
  pkg/cvo/updatepayload.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#298 Bug 1791863: lib/resourcemerge/core: Clear livenessProbe and readinessProbe if nil in required
  lib/resourcemerge/core.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#303 Bug 1793051: cvo: pass limiter when creating a store
  pkg/verify/verifyconfigmap/store.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#308 Bug 1793209: Don't use protobuf client for SecurityContextConstraints
  lib/resourcebuilder/security.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#302 Bug 1790629: use st.Manifest.OriginalFilename if object doesn't have a name
  pkg/payload/task.go
  pkg/payload/task_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
