Repository openshift/cluster-version-operator, pull requests merged in 2020-04, with the labels that each got.

#344 OWNERS: Add component Cluster Version Operator
  OWNERS
Labels: approved, lgtm

#347 OWNERS: Document 'component' property
  OWNERS
Labels: approved, lgtm

#318 cvo: When installing or upgrading, fast-fill cluster-operators
  lib/resourcebuilder/interface.go
  pkg/cvo/cvo.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
Labels: approved, lgtm, size/M

#350 docs/dev/clusteroperator.md: Change Failing to Degraded
  docs/dev/clusteroperator.md
Labels: approved, lgtm, retest-not-required-docs-only

#346 pkg/cvo/sync_worker: Fix "successfull" -> "successful" typo
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, retest-not-required-docs-only

#345 pkg/cvo/updatepayload: Fix "deafult" -> "default" typo
  pkg/cvo/updatepayload.go
Labels: approved, lgtm

#343 Do not report errors to status loop on progressing
  lib/resourcebuilder/apps.go
Labels: approved, lgtm

#185 Bug 1825003: pkg/payload/task: Include name/reason in "unknown error" message
  pkg/payload/task.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#339 Using optr.queue.ShutDown directly as upstream K8s is fixed now
  pkg/cvo/cvo.go
Labels: approved, lgtm

#351 Add LalatenduMohanty to the owner list
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only

#352 Bug 1825512: Support v1 crds in manifests
  lib/resourceread/apiext.go
  lib/resourceread/apiext_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#360 Bug 1827166: pkg/cvo/sync_worker: Log precondition handling
  pkg/cvo/sync_worker.go
  pkg/payload/precondition/clusterversion/upgradeable.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#363 Update readme to include fast fill logic
  docs/dev/clusteroperator.md
Labels: approved, bugzilla/valid-bug, lgtm
