Repository openshift/cluster-version-operator, pull requests merged in 2020-02, with the labels that each got.

#282 Bug 1783221: lib/resourcemerge/core: Fix panic on container/port removal
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#258 Bug 1795412: Print whether CRDs are updated
  lib/resourceapply/apiext.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#291 Bug 1797624: loosen upgradeable condition to allow z-level upgrades
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/precondition/clusterversion/upgradable_test.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/precondition.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#312 Bug 1794823: lib/resourcemerge: Do not attempt to change Job's immutable spec.selector
  docs/user/reconciliation.md
  lib/resourcemerge/batch.go
  lib/resourcemerge/batch_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#319 Bug 1797806: metrics: include upi installs in cluster_installer
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/internal/constants.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#320 OWNERS: Add Scott Dodson as an approver
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#322 Bug 1801300: lib/resourcemerge: remove ports which are no longer required
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#323 Bug 1802710: lib/resourcemerge: remove ports which are no longer required
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#317 bug 1794817: lib/resourcebuilder/batch.go: skip waiting for job to complete when in Init mode
  lib/resourcebuilder/batch.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#326 Bug 1782982: pkg/verify/verifyconfigmap: Use {algo}-{hash} prefixes
  pkg/verify/verifyconfigmap/store.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#327 Bug 1782982: pkg/verify/verifyconfigmap: Fix Store to use {algo}-{hash} prefix
  pkg/verify/verifyconfigmap/store.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#325 Bug 1802248: lib/resourcemerge: remove ports which are no longer required
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#316 Bug 1768260: lib,pkg: provide detailed errors for workload failures
  lib/resourcebuilder/apps.go
  pkg/payload/task.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#328 Bug 1805172: pkg/verify/verifyconfigmap: Add klog logging
  pkg/verify/verifyconfigmap/store.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#314 Bug 1800346: lib/resourcemerge/core: Fix panic on container removal
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#331 OWNERS: add OTA team members to approvers list
  OWNERS
Labels: approved, lgtm, retest-not-required-docs-only, size/XS
