Repository openshift/cluster-version-operator, pull requests merged in 2020-08, with the labels that each got.

#419 *: Port from Update to Release for ClusterVersion status
  docs/user/status.md
  go.mod
  go.sum
  pkg/autoupdate/autoupdate.go
  pkg/autoupdate/autoupdate_test.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
  pkg/cvo/testdata/paralleltest/release-manifests/release-metadata
  pkg/cvo/testdata/payloadtest-2/release-manifests/release-metadata
  pkg/cvo/testdata/payloadtest/release-manifests/release-metadata
  pkg/cvo/updatepayload.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/start/start_integration_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#422 Bug 1862524: pkg/cvo/status: Raise Operator leveling grace-period to 20 minutes
  docs/user/status.md
  pkg/cvo/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#423 pkg/cincinnati/cincinnati: Change "installed" -> "reconciling" for VersionNotFound
  docs/user/status.md
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
Labels: approved, lgtm

#426 Bug 1843505: Have the leader election use faster defaults
  pkg/start/start.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#425 pkg/cvo: Fix maxRetries comment (not about machineconfig pools)
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
Labels: approved, lgtm

#432 b/install/0000_90_cluster-version-operator_02_servicemonitor: > 0 for UpdateAvailable
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm

#428 Bug 1866554: lib/resourcemerge/core: set ShareProcessNamespace, DNSConfig and TerminationGracePeriodSeconds
  lib/resourcemerge/core.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#430 lib/resourcebuilder/apps: Only error on Deployment Available=False *and* Progressing=False
  lib/resourcebuilder/apps.go
Labels: approved, lgtm

#413 Changes to verify package in preparation for move to library-go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/verify/configmap.go
  pkg/verify/configmap_test.go
  pkg/verify/store/configmap/configmap.go
  pkg/verify/store/sigstore/sigstore.go
  pkg/verify/testdata/manifests/loads-valid.yaml
  pkg/verify/testdata/manifests/only-first-used.yaml
  pkg/verify/testdata/manifests/requires-data.yaml
  pkg/verify/testdata/manifests/requires-stores.yaml
  pkg/verify/testdata/manifests/requires-verifiers.yaml
  pkg/verify/util/encode.go
  pkg/verify/util/util.go
  pkg/verify/verify.go
Labels: approved, lgtm

#439 docs/dev/operators: Replace stale manifest filename regexp with generic discussion
  docs/dev/operators.md
Labels: approved, lgtm

#427 Bug 1866480: pkg/cvo/status: Raise Operator leveling grace-period to 20 minutes
  docs/user/reconciliation.md
  docs/user/status.md
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#441 Bug 1797123: pkg/cvo: Separate ConfigMap informer for openshift-config-managed
  pkg/cvo/cvo.go
  pkg/start/start.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#424 Bug 1843505: pkg/start: Release leader lease on graceful shutdown
  bootstrap/bootstrap-pod.yaml
  cmd/start.go
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#444 Bug 1872080: Dockerfile.rhel: Use a RHEL-version-agnostic filename
  Dockerfile.rhel
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#448 Bug 1873900: install/0000_00_cluster-version-operator_03_deployment: Bump to --v=5
  bootstrap/bootstrap-pod.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
