Repository openshift/cluster-version-operator, pull requests merged in 2020-07, with the labels that each got.

#349 pkg/cvo/metrics: Graceful server shutdown
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/egress.go
  pkg/cvo/metrics.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#396 pkg/verify/store/sigstore: Factor HTTP store into its own package
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/verify/configmap.go
  pkg/verify/configmap_test.go
  pkg/verify/store/sigstore/client.go
  pkg/verify/store/sigstore/sigstore.go
  pkg/verify/store/sigstore/sigstore_test.go
  pkg/verify/verify.go
  pkg/verify/verify_test.go
Labels: approved, lgtm

#401 lib/resourcebuilder/apps: Explicit mode instead of 'Generation > 1'
  lib/resourcebuilder/apps.go
Labels: approved, lgtm

#407 Fixing a command in reconciliation document
  docs/user/reconciliation.md
Labels: approved, lgtm, retest-not-required-docs-only

#408 Bug 1855577: Updating the golang.org/x/text version to v0.3.3
  go.mod
  go.sum
  vendor/golang.org/x/text/transform/transform.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables11.0.0.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#405 vendor: Port to blang/semver v4
  go.mod
  go.sum
  lib/validation/validation.go
  pkg/autoupdate/autoupdate.go
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/version/version.go
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/modules.txt
Labels: approved, lgtm

#394 Bug 1822513: Determine current version by checking for status completed
  pkg/payload/precondition/clusterversion/upgradable_test.go
  pkg/payload/precondition/clusterversion/upgradeable.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#412 update CVO to inject internal loadbalancer for use by the CVO pod
  install/0000_00_cluster-version-operator_03_deployment.yaml
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/podspec.go
  lib/resourcebuilder/podspec_test.go
Labels: approved, lgtm

#403 lib/resourcebuilder/apiext: Error on unrecognized CRD version
  lib/resourcebuilder/apiext.go
Labels: approved, lgtm

#414 Dockerfile*: Bump to Go 1.14
  Dockerfile
  Dockerfile.rhel7
  vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables12.0.0.go
Labels: approved, lgtm

#364 Bug 1822844: Block z level upgrades when ClusterVersionOverridesSet is set
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/precondition/clusterversion/upgradable_test.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/precondition.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#411 emit events for each new payload
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#418 pkg/cvo/cvo_scenarios_test: Fix "Retrive" -> "Retrieve" typo
  pkg/cvo/cvo_scenarios_test.go
Labels: approved, lgtm

#421 pkg/cvo/cvo_test: Distinguish names for the "single clusteroperator" cases
  pkg/cvo/cvo_test.go
Labels: approved, lgtm

#400 lib/resourcebuilder: Replace wait-for with single-shot "is it alive now?"
  lib/resourcebuilder/apiext.go
  lib/resourcebuilder/apps.go
  lib/resourcebuilder/batch.go
Labels: approved, lgtm

#410 Use context to add timeout to cincinnati HTTP request
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
Labels: approved, lgtm

#311 Bug 1797123: pkg/cvo: Fetch proxy CA certs from openshift-config-managed/trusted-ca-bundle
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/egress.go
  pkg/internal/constants.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, size/M
