Repository openshift/cluster-version-operator, pull requests merged in 2021-12, with the labels that each got.

#698 Bug 2028217: lib/resourcemerge/apps: Default Deployment replicas to one
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#623 Bug 2020107: Remove run-level label
  install/0000_00_cluster-version-operator_00_namespace.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#703 Bug 2026560: lib/resourcemerge/core: Merge volumeMounts by mountPath
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#694 Exclude featuregate.release.openshift/tech-preview=true manifests
  hack/cluster-version-util/task_graph.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
  pkg/featurechangestopper/techpreviewchangestopper.go
  pkg/featurechangestopper/techpreviewchangestopper_test.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/task_graph_test.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#706 pkg/start: Log and continue when we fail to retrieve the feature gate
  pkg/featurechangestopper/techpreviewchangestopper.go
  pkg/start/start.go
Labels: approved, lgtm

#707 Bug 2029785: pkg/cincinnati: Fix panic for conditional edges overlapping with unconditional edges
  pkg/cincinnati/cincinnati.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#708 pkg/payload/precondition: File shuffling, drop ClusterVersion argument, etc.
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/precondition/clusterversion/etcdbackup.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/clusterversion/upgradeable_test.go
  pkg/payload/precondition/precondition.go
  pkg/payload/precondition/precondition_test.go
Labels: approved, lgtm

#702 Bug 2028602: lib/resourcemerge/apps: Default Deployment replicas to one
  lib/resourcemerge/apps.go
  lib/resourcemerge/apps_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed

#718 Bug 2033745: pkg/cvo/availableupdates: Acount for default upstream in recent-change throttling
  pkg/cvo/availableupdates.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
