Repository openshift/cluster-version-operator, pull requests merged in 2021-05, with the labels that each got.

#554 Bug 1957991: install/0000_90_cluster-version-operator_02_servicemonitor: Soften ClusterOperatorDegraded
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#553 Bug 1957775: pkg/cvo/sync_worker: Shift ClusterOperator pre-creation into the manifest-task node
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#556 Bug 1957991: install/0000_90_cluster-version-operator_02_servicemonitor: Update ClusterOperatorDegraded message to 30m
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#558 Bug 1881481: Only compare ServiceType when set in manifest
  lib/resourceapply/core.go
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#560 Bug 1927168: pkg/cvo/internal/operatorstatus: Replace wait-for with single-shot "is it alive now?"
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#565 Bug 1960554: Remove rbacv1beta1 support
  hack/generate-lib-resources.py
  lib/resourceapply/rbacv1beta1.go
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcemerge/rbacv1beta1.go
  lib/resourceread/resourceread.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#564 Dockerfile*: Bump to Go 1.16
  Dockerfile
  Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm

#562 Bug 1881520: avoid hotlooping on RoleBindings with empty APIGroup
  lib/resourcemerge/rbac.go
  lib/resourcemerge/rbac_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#563 Bug 1881481: TargetPort should default to port in ServicePort if unset
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#569 Bug 1927168: pkg/cvo/sync_worker: Increment Attempt on failed reconciliation
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#571 Bug 1962882: pkg/cvo/updatepayload: Set priorityClassName for the version Job
  pkg/cvo/updatepayload.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#524 Update a doc example to match modern OCP
  docs/dev/clusterversion.md
Labels: approved, bugzilla/valid-bug, lgtm, lifecycle/stale
