Repository openshift/cluster-version-operator, pull requests merged in 2021-02, with the labels that each got.

#484 Bug 1903382: pkg/payload/task_graph: Require firstIncompleteNode to have tasks
  pkg/payload/task_graph.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#486 Bug 1884334: UpdateError: enhance for ability to determine when upgrade failing
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/payload/task.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#501 Bug 1916384: pkg/cvo: Use shutdownContext for final status synchronization
  pkg/cvo/cvo.go
  pkg/start/start.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#508 Bug 1921413: pkg/cvo/cvo: Guard Operator.Run goroutine handling from early cancels
  pkg/cvo/cvo.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#511 pkg/cvo/updatepayload: Fix "verifcation" -> "verification" typo
  pkg/cvo/updatepayload.go
Labels: approved, lgtm

#509 Bug 1926310: install/0000_90_cluster-version-operator_02_servicemonitor.yaml: adjust "CannotRetrieveUpdates" to "warning"
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#431 pkg/cvo/sync_worker: Make expected/actual version mismatch fatal
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#453 pkg/cvo/metrics: Log metrics-server shutdown
  pkg/cvo/metrics.go
Labels: approved, lgtm

#459 pkg/cvo/upgradeable: Fix "Upgradebale" -> "Upgradeable"
  pkg/cvo/upgradeable.go
Labels: approved, lgtm

#519 Bug 1927944: pkg/start: Fix shutdown deadlock when die before getting a leader lock
  pkg/start/start.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#513 pkg/payload/task: Fix UpdateEffectType const comments
  pkg/payload/task.go
Labels: approved, lgtm

#506 Bug 1921180: pkg/cvo/sync_worker.go: Ignore work changes during init
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#523 pkg/cvo: Add logging to track ClusterVersion
  pkg/cvo/cvo.go
  pkg/cvo/status.go
Labels: approved, lgtm

#512 Bug 1925199: add current profile annotations to CVO manifests
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_02_roles.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_90_cluster-version-operator_00_prometheusrole.yaml
  install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  install/0001_00_cluster-version-operator_03_service.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#521 Bug 1921413: pkg/start: Fix shutdown deadlock when die before getting a leader lock
  pkg/start/start.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#525 Bug 1931025: pkg/cvo: Use shutdownContext for final status synchronization
  pkg/cvo/cvo.go
  pkg/start/start.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
