Repository openshift/cluster-version-operator, pull requests merged in 2021-01, with the labels that each got.

#404 Bug 1907329: Add cluster profile support
  hack/cluster-version-util/task_graph.go
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_02_roles.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_90_cluster-version-operator_00_prometheusrole.yaml
  install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  install/0001_00_cluster-version-operator_03_service.yaml
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/testdata/manifests/loads-valid.yaml
  pkg/cvo/testdata/manifests/requires-data.yaml
  pkg/cvo/testdata/paralleltest/release-manifests/0000_10_a_file.yaml
  pkg/cvo/testdata/paralleltest/release-manifests/0000_20_a_file.yaml
  pkg/cvo/testdata/paralleltest/release-manifests/0000_20_b_file.yaml
  pkg/cvo/testdata/payloadtest-2/release-manifests/0000_10_a_file
  pkg/cvo/testdata/payloadtest-2/release-manifests/0000_10_a_file.json
  pkg/cvo/testdata/payloadtest-2/release-manifests/0000_10_a_file.yaml
  pkg/cvo/testdata/payloadtest-2/release-manifests/0000_10_a_file.yml
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file.json
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file.yaml
  pkg/cvo/testdata/payloadtest/release-manifests/0000_10_a_file.yml
  pkg/cvo/testdata/payloadtest/release-manifests/0000_20_a_exclude.yml
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/render.go
  pkg/payload/task_graph_test.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#493 Bug 1906100: use child context to verify payload signature on forced update
  pkg/cvo/updatepayload.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#496 *: Replace registry.svc.ci.openshift.org with registry.ci.openshift.org
  Dockerfile
  Dockerfile.rhel
  README.md
  docs/dev/clusterversion.md
  docs/dev/operators.md
  docs/user/reconciliation.md
Labels: approved, bugzilla/valid-bug, lgtm

#492 Bug 1905221: pkg/cvo/sync_worker.go: log work change details
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#500 Bug 1905221: pkg/cvo/sync_worker.go: Ignore work changes during init
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#503 Bug 1918085: Fixing the log message in WaitForJobCompletion()
  lib/resourcebuilder/batch.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#497 Bug 1768255: replace Fraction with Done and Total
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#502 *: Replace registry.svc.ci.openshift.org with registry.ci.openshift.org
  Dockerfile
  Dockerfile.rhel
  README.md
  docs/dev/clusterversion.md
  docs/dev/operators.md
  docs/user/reconciliation.md
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#507 Bug 1921277: pkg/cvo/sync_worker.go: Fix log statements to handle arguments
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
