Repository openshift/cluster-version-operator, pull requests merged in 2021-03, with the labels that each got.

#529 Revert "Merge pull request #523 from jottofar/cv-logging"
  pkg/cvo/cvo.go
  pkg/cvo/status.go
Labels: approved, lgtm

#522 Use profile from the installer to render CVO manifests
  bootstrap/bootstrap-pod.yaml
  cmd/render.go
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/payload/payload.go
  pkg/payload/render.go
Labels: approved, lgtm

#514 pkg/cvo/internal/operatorstatus: Change nested message
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
Labels: approved, lgtm

#531 Bug 1929917: pkg/cvo/sync_worker: Skip precreation of baremetal ClusterOperator
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#530 pkg/cvo/metrics: Exclude unrecognized statuses from cluster_operator_conditions
  pkg/cvo/metrics.go
Labels: approved, lgtm

#528 Bug 1871303: metrics: serve metrics after leader lock acquired
  pkg/cvo/metrics.go
  pkg/start/start.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#538 Document impact of upgradeable condition on the ability to begin an upgrade
  docs/dev/clusteroperator.md
Labels: approved, lgtm

#537 Bug 1938947: Ensure automountServiceAccountToken is synced on service account updates
  lib/resourceapply/core.go
  lib/resourcemerge/core.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
