Repository openshift/cluster-version-operator, pull requests merged in 2021-06, with the labels that each got.

#552 hack/generate-lib-resources: Use library-go manifests
  hack/generate-lib-resources.py
Labels: approved, bugzilla/valid-bug, lgtm

#579 Bug 1881514: Prevent hotlooping in ImageStreams
  hack/generate-lib-resources.py
  lib/resourceapply/imagestream.go
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcemerge/imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/image.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagetag.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#578 Bug 1941901: lib/resourcemerge/core: Fix toleration matching logic
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#559 Bug 1881484: Set defaults in deployment
  lib/resourcemerge/apps_test.go
  lib/resourcemerge/batch_test.go
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#581 docs/dev: Fix code block brackets in run-cvo-locally.md
  docs/dev/run-cvo-locally.md
Labels: approved, bugzilla/valid-bug, lgtm

#585 Bug 1946479: prevent pod deployment deadlock due to custom SA projected volume injection
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#561 Bug 1879184: Log object updates and show existing/required diff
  lib/resourceapply/apiext.go
  lib/resourceapply/apireg.go
  lib/resourceapply/apps.go
  lib/resourceapply/batch.go
  lib/resourceapply/core.go
  lib/resourceapply/cv.go
  lib/resourceapply/rbac.go
  lib/resourceapply/security.go
  pkg/cvo/internal/generic.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#587 Bug 1969501: install/0000_90_cluster-version-operator_02_servicemonitor: Soften ClusterOperatorDegraded
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#590 Correctly initialize service host and port when environment is missing
  lib/resourcebuilder/podspec.go
  lib/resourcebuilder/podspec_test.go
Labels: approved, lgtm

#595 README: Update the link to the rendering release image locally header
  README.md
Labels: approved, lgtm

#592 Simplify the comparison between SyncWork references
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#607 Revert "prevent pod deployment deadlock due to custom SA projected volume injection"
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm

#566 Bug 1960559: drop APIExtensions v1beta1
  hack/generate-lib-resources.py
  lib/resourceapply/apiext.go
  lib/resourceapply/apireg.go
  lib/resourceapply/apiregv1beta1.go
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcemerge/apiext.go
  lib/resourcemerge/apireg.go
  lib/resourcemerge/apiregv1beta1.go
  lib/resourceread/resourceread.go
  pkg/cvo/cvo_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#547 install/0000_90_cluster-version-operator_02_servicemonitor: Alert summary/descriptions
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm

#598 Added golangci-lint with most linters disabled
  .golangci.yaml
  Makefile
  hack/golangci-lint.sh
Labels: approved, lgtm

#597 Fixed fake client for CVO scenarios test
  pkg/cvo/cvo_scenarios_test.go
Labels: approved, lgtm

#611 pkg/cvo/upgradeable: Soften "cannot be upgraded" to "should not be upgraded"
  pkg/cvo/cvo_test.go
  pkg/cvo/upgradeable.go
Labels: approved, lgtm

#596 Docs: Adding the update workflow
  README.md
  docs/dev/clusteroperator.md
  docs/user/update-workflow.md
Labels: approved, lgtm

#438 OTA-222: Add a manifest annotation to be used for object deletion
  docs/dev/object-deletion.md
  docs/dev/operators.md
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcedelete/apiext.go
  lib/resourcedelete/apireg.go
  lib/resourcedelete/apps.go
  lib/resourcedelete/batch.go
  lib/resourcedelete/core.go
  lib/resourcedelete/helper.go
  lib/resourcedelete/helper_test.go
  lib/resourcedelete/rbac.go
  lib/resourcedelete/security.go
  pkg/cvo/internal/generic.go
  pkg/cvo/upgradeable.go
Labels: approved, lgtm

#602 Enable gosimple
  .golangci.yaml
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
Labels: approved, lgtm

#600 Enable errcheck linter
  .golangci.yaml
  cmd/main.go
  cmd/render.go
  pkg/cvo/sync_test.go
  pkg/payload/precondition/clusterversion/upgradable_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#605 Enable structcheck
  .golangci.yaml
  pkg/autoupdate/autoupdate.go
  pkg/cvo/cvo.go
Labels: approved, lgtm

#606 Enable unused
  .golangci.yaml
  pkg/cvo/cvo_test.go
  pkg/cvo/status_test.go
  pkg/cvo/sync_test.go
Labels: approved, lgtm

#603 Enable govet
  .golangci.yaml
  pkg/cvo/cvo_test.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/status_test.go
  pkg/cvo/sync_test.go
Labels: approved, lgtm

#601 Enable gofmt
  .golangci.yaml
  lib/resourcemerge/core_test.go
Labels: approved, lgtm

#599 Enable deadcode linter
  .golangci.yaml
  lib/resourcemerge/core.go
  lib/validation/validation.go
  pkg/cvo/cvo_test.go
  pkg/cvo/internal/generic.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/sync_worker.go
  pkg/payload/task_graph.go
Labels: approved, lgtm

#604 Enable staticcheck
  .golangci.yaml
  cmd/image.go
  pkg/cvo/egress.go
Labels: approved, lgtm

#616 Fix more golangci-lint issues
  lib/resourcedelete/helper_test.go
  pkg/payload/precondition/precondition_test.go
Labels: approved, lgtm

#526 Remove toleration of unschedulable
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm

#618 Bug 1976307: add ImageStreams manifest delete annotation logic
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcedelete/imagestream.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#617 Added ownerReference to all objects created and managed by CVO
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm
