Repository openshift/cluster-version-operator, pull requests merged in 2021-07, with the labels that each got.

#619 Enable misspell linter
  .golangci.yaml
  lib/resourcebuilder/interface.go
  pkg/cvo/internal/generic.go
  pkg/cvo/metrics.go
  pkg/cvo/sync_test.go
  pkg/cvo/updatepayload.go
Labels: approved, lgtm

#621 Bug 1978774: pkg/cvo/egress: Load HTTPS proxy from Proxy status
  pkg/cvo/egress.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#622 Bug 1978749: pkg/cvo: Respect noProxy
  go.mod
  go.sum
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/egress.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/image.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagetag.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#613 Added waitgroups for autoupdate workers to complete before stopping
  pkg/autoupdate/autoupdate.go
Labels: approved, lgtm

#614 Bug 1970421: Do not check if Job has Failed count set
  lib/resourcebuilder/batch.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#628 Bug 1984414: Log resource diffs on update only in reconcile mode
  lib/resourceapply/apiext.go
  lib/resourceapply/apps.go
  lib/resourceapply/batch.go
  lib/resourceapply/core.go
  lib/resourceapply/cv.go
  lib/resourceapply/imagestream.go
  lib/resourceapply/rbac.go
  lib/resourceapply/security.go
  lib/resourcebuilder/podspec_test.go
  lib/resourcebuilder/resourcebuilder.go
  pkg/cvo/internal/generic.go
  pkg/cvo/internal/generic_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#631 tombstone previous docs location with link to openshift/enhancements.
  docs/dev/README.md
  docs/dev/clusteroperator.md
  docs/dev/clusterversion.md
  docs/dev/metrics.md
  docs/dev/object-deletion.md
  docs/dev/operators.md
  docs/dev/upgrades.md
  docs/user/README.md
  docs/user/reconciliation.md
  docs/user/status.md
  docs/user/update-workflow.md
Labels: approved, lgtm

#629 Bug 1982046: lib/resourcedelete: Always check delete progress
  lib/resourcedelete/apiext.go
  lib/resourcedelete/apireg.go
  lib/resourcedelete/apps.go
  lib/resourcedelete/batch.go
  lib/resourcedelete/core.go
  lib/resourcedelete/imagestream.go
  lib/resourcedelete/rbac.go
  lib/resourcedelete/security.go
  pkg/cvo/internal/generic.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#632 Update the doc links in Readme
  README.md
Labels: approved, bugzilla/valid-bug, lgtm
