Repository openshift/cluster-version-operator, pull requests merged in 2021-11, with the labels that each got.

#684 Bug 1878925: pkg/cvo/updatepayload: Drop history from target pullspec lookup
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#681 Adding docs to test CVO with custom update graph
  docs/dev/feed-cvo-custom-graphs.md
Labels: approved, lgtm

#685 install: Drop single-node-developer profile
  install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
Labels: approved, lgtm

#646 install/0000_00_cluster-version-operator_03_deployment: Set dnsPolicy: ClusterFirstWithHostNet
  bootstrap/bootstrap-pod.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm

#669 Bug 1990635: Fixing the sync issue when desired version and channel changed at the same time
  pkg/cvo/cvo.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#679 [release-4.8] Bug 2015025: lib/resourcemerge/imagestream.go: Copy all data for new tag reference
  lib/resourcemerge/imagestream.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#689 Bug 2022509: cvo: Compare manifest group in getOverrideForManifest
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#686 install: Add description annotations to manifests
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
  install/0000_00_cluster-version-operator_02_roles.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_90_cluster-version-operator_00_prometheusrole.yaml
  install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  install/0001_00_cluster-version-operator_03_service.yaml
Labels: approved, lgtm

#659 Bug 2005407: Changing the ClusterNotUpgradeable alert to info
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#663 Targeted edge blocking
  cmd/main.go
  go.mod
  go.sum
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/clusterconditions/always/always.go
  pkg/clusterconditions/cache/cache.go
  pkg/clusterconditions/cache/cache_test.go
  pkg/clusterconditions/clusterconditions.go
  pkg/clusterconditions/clusterconditions_test.go
  pkg/clusterconditions/mock/mock.go
  pkg/clusterconditions/mock/mock_test.go
  pkg/clusterconditions/promql/promql.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo_test.go
  vendor/github.com/jpillora/backoff/LICENSE
  vendor/github.com/jpillora/backoff/README.md
  vendor/github.com/jpillora/backoff/backoff.go
  vendor/github.com/jpillora/backoff/go.mod
  vendor/github.com/mwitkow/go-conntrack/.gitignore
  vendor/github.com/mwitkow/go-conntrack/.travis.yml
  vendor/github.com/mwitkow/go-conntrack/LICENSE
  vendor/github.com/mwitkow/go-conntrack/README.md
  vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
  vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
  vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
  vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/common/config/config.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/golang.org/x/net/internal/timeseries/timeseries.go
  vendor/golang.org/x/net/trace/events.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/net/trace/trace.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: approved, lgtm

#696 Bug 2025955: Removing the extra indentation
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#695 Bumping the GOLANGCI_LINT_VERSION to v1.43.0
  Makefile
Labels: approved, lgtm

#691 Bug 1982683: [release-4.8] Respect noProxy
  go.mod
  go.sum
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/egress.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/image.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/listers/image/v1/imagetag.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#697 Bug 2027585: pkg/cincinnati: Fix panic for conditional edges with risks after an invalid risk
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
