Repository openshift/cluster-version-operator, pull requests merged in 2021-04, with the labels that each got.

#533 Bug 1940652: Bump logging to --v=5
  bootstrap/bootstrap-pod.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#541 docs/user/status: Mention channel-clearing for VersionNotFound
  docs/user/status.md
Labels: approved, lgtm

#544 lib/resourcemerge/rbac: Reconcile ClusterRole.AggregationRule
  lib/resourcemerge/rbac.go
  lib/resourcemerge/rbacv1beta1.go
Labels: approved, lgtm

#527 pkg/cvo/internal/operatorstatus: Drop deprecated failing/progressing handling
  docs/user/reconciliation.md
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm

#542 docs/user/reconciliation: Add some English to the release image inspection
  docs/user/reconciliation.md
Labels: approved, lgtm

#540 Bug 1943973: pkg/cvo/sync_worker: Skip precreation of baremetal ClusterOperator
  pkg/cvo/sync_worker.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#543 Add management workload annotations
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#481 Bug 1950430: pkg/cvo/metrics: Drop HTTP, require HTTPS for metrics access
  bootstrap/bootstrap-pod.yaml
  cmd/start.go
  go.mod
  go.sum
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/cvo/metrics.go
  pkg/start/start.go
  vendor/github.com/cockroachdb/cmux/.gitignore
  vendor/github.com/cockroachdb/cmux/.travis.yml
  vendor/github.com/cockroachdb/cmux/CONTRIBUTORS
  vendor/github.com/cockroachdb/cmux/LICENSE
  vendor/github.com/cockroachdb/cmux/README.md
  vendor/github.com/cockroachdb/cmux/buffer.go
  vendor/github.com/cockroachdb/cmux/cmux.go
  vendor/github.com/cockroachdb/cmux/doc.go
  vendor/github.com/cockroachdb/cmux/matchers.go
  vendor/github.com/cockroachdb/cmux/patricia.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, lifecycle/rotten

#549 Bug 1951339: lib/resourcemerge/core: Clear env and envFrom if unset in manifest
  lib/resourcebuilder/apps.go
  lib/resourcemerge/core.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#548 Rename workload annotations
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#550 Bug 1834551: pkg/cvo/metrics: Ignore Degraded for cluster_operator_up
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
