Repository openshift/cluster-version-operator, pull requests merged in 2021-09, with the labels that each got.

#640 pkg/cvo: Drop the explicit 'upstream' from our replacement ClusterVersion
  pkg/cvo/cvo.go
Labels: approved, lgtm

#627 Bug 1980411: [release-4.8] pkg/cvo/egress: Load HTTPS proxy from Proxy status
  pkg/cvo/egress.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved

#649 Bug 1999777: Ensure recent etcd backup before allowing minor-version updates
  pkg/cvo/cvo.go
  pkg/payload/precondition/clusterversion/upgradeable.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#654 Bug 2002834: lib/resourcemerge/core: Remove unrecognized volumes and mounts
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#656 OWNERS: Prune crawford
  OWNERS
Labels: approved

#660 Bug 2005581: install/0000_00_cluster-version-operator_03_deployment: Explicit kube-api-access
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#661 Bug 2006145: install/0000_00_cluster-version-operator_03_deployment: Explicit kube-api-access
  install/0000_00_cluster-version-operator_03_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved

#652 Bug 1961341: Remove rbacv1beta1 support
  hack/generate-lib-resources.py
  lib/resourceapply/rbacv1beta1.go
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcemerge/rbacv1beta1.go
  lib/resourceread/resourceread.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#665 .ci-operator: Bump to Go 1.16
  .ci-operator.yaml
Labels: approved, lgtm

#667 Unset listen option while running CVO locally [doc/dev]
  docs/dev/run-cvo-locally.md
Labels: approved, needs-ok-to-test, lgtm

#647 Bug 1999092: Add and enable admin ack Upgradeable condition gate
  install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/upgradeable.go
  pkg/internal/constants.go
  pkg/payload/precondition/clusterversion/upgradable_test.go
  pkg/payload/precondition/clusterversion/upgradeable.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent
