Repository openshift/cluster-version-operator, pull requests merged in 2022-07, with the labels that each got.

#786 Bug 2091806: pkg/cvo: Separate payload load from payload apply
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#804 Bug 2108858: lib/resourcemerge: change SecurityContext reconcile
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
  lib/resourcemerge/meta_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#788 Bug 2094174: pkg/cvo: reset payload load status
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#806 Bug 2109374: pkg/clusterconditions/promql: Cap PromQL queries at 5 minutes
  pkg/clusterconditions/promql/promql.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#807 Bug 2110590: pkg/cvo/updatepayload: Set 'readOnlyRootFilesystem: false'
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
