Repository openshift/cluster-version-operator, pull requests merged in 2022-06, with the labels that each got.

#783 Bug 2091770: pkg/cvo/updatepayload: Guard against 'rm -fR -whatever' with ./*
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#782 Bug 2090150: pkg/cvo/sync_worker.go: Save overrides
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#791 Bug 2097067: pkg/cvo: retain initial completed update history entry
  pkg/cvo/status.go
  pkg/cvo/status_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
