Repository openshift/cluster-version-operator, pull requests merged in 2022-02, with the labels that each got.

#719 pkg/cvo: Drop unused 'workers' argument from Operator.Run
  pkg/cvo/cvo.go
  pkg/start/start.go
Labels: approved, lgtm

#733 Bug 2009845: pkg/cvo/sync_worker: Use current state, not suggested state, for guarding Initializing->Updating
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#736 Bug 2050946: pkg/featurechangestopper: Seed queue to guard against incorrect startingTechPreviewState
  pkg/featurechangestopper/techpreviewchangestopper.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#737 vendor: Bump openshift/api to pick up capabilities
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#712 pkg/payload: Log manifest exclusion
  pkg/payload/payload.go
  pkg/payload/payload_test.go
Labels: approved, lgtm

#745 Bug 1822752: pkg/cvo: Fix ups from separating load from apply #683
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
