Repository openshift/cluster-version-operator, pull requests merged in 2022-03, with the labels that each got.

#740 Bug 2053359: Feature gate initialization
  pkg/featurechangestopper/techpreviewchangestopper.go
  pkg/start/start.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#741 Get cluster version object earlier in startup
  bootstrap/bootstrap-pod.yaml
  cmd/start.go
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#748 Bug 2062568: lib/resourcebuilder/batch: Stop waiting on Job deadline exceeded
  lib/resourcebuilder/batch.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#744 Consume post install static spec capabilities
  hack/cluster-version-util/task_graph.go
  lib/capability/capability.go
  lib/capability/capability_test.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/task_graph_test.go
Labels: approved, lgtm

#749 pkg/payload: Log load-time manifest exclusion at V(2)
  pkg/payload/payload.go
Labels: approved, lgtm

#750 pkg/cvo/sync_worker.go: ensure all of SyncWorkerStatus copied
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#752 lib/capability: Sort status.capabilities arrays
  lib/capability/capability.go
Labels: approved, lgtm

#751 vendor: update openshift/api
  go.mod
  go.sum
  lib/capability/capability_test.go
  pkg/cvo/cvo_scenarios_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image_digest_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_image_tag_mirror_set.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#755 pkg/cvo/metrics: Add a cluster_version_capability metric
  pkg/cvo/metrics.go
Labels: approved, lgtm

#757 Bump openshift/api to include new marketplace capability
  go.mod
  go.sum
  lib/capability/capability_test.go
  pkg/cvo/cvo_scenarios_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_node.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm
