Repository openshift/cluster-version-operator, pull requests merged in 2022-04, with the labels that each got.

#754 capability: disallow disabling, add enabling capabilities
  go.mod
  go.sum
  hack/cluster-version-util/task_graph.go
  lib/capability/capability.go
  lib/capability/capability_test.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/task_graph_test.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
  vendor/modules.txt
Labels: approved, lgtm

#760 Bug 2070805: pkg/cvo/updatepayload: Prune previous payload downloads
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#762 pkg/cvo/sync_worker: Log only changed enabled capabilities
  lib/capability/capability.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#761 Bug 2070887: pkg/cvo/sync_worker.go: set implicitly enabled caps earlier
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#758 Implicitly enable capabilities on updates
  go.mod
  go.sum
  lib/capability/capability.go
  lib/capability/capability_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/testdata/payloadcapabilitytest/test1/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test1/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test2/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test2/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test3/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test3/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test4/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test4/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test5/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test5/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test6/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test6/current/file_2.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test6/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test6/update/file_2.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/current/file_2.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/current/file_3.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/current/file_4.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/current/file_5.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/current/file_6.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/update/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/update/file_2.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/update/file_3.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/update/file_4.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/update/file_5.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test7/update/file_6.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test8/current/file_1.yaml
  pkg/cvo/testdata/payloadcapabilitytest/test9/update/file_1.yaml
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
  vendor/modules.txt
Labels: approved, lgtm

#759 Bug 2070854: syncWorkerStatus: Avoid saving stale status values
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#765 Bug 2070805: pkg/cvo/updatepayload: Shift previous-download removal into the job
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#767 Bug 2070805: pkg/cvo/updatepayload: Restore shell for rm globbing
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#766 Bug 2072389: Do not save desired update on load failures
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#768 Bug 2079789: pkg/cvo/sync_worker.go: Initialize implicitlyEnabledCaps
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
