Repository openshift/cluster-version-operator, pull requests merged in 2022-12, with the labels that each got.

#872 Build CVO from UBI8 instead of obsolete `origin-v4.0:base`
  Dockerfile
Labels: approved, lgtm

#869 OTA-560: Modernize README.md to be user-centered
  README.md
Labels: approved, lgtm

#874 OCPBUGS-1443: Avoid using a lister before client caches sync
  pkg/cvo/upgradeable.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-low

#871 OTA-560: Improve developer-oriented docs
  CONTRIBUTING.md
  Makefile
  docs/dev/README.md
  hack/build-image.sh
  hack/update-codegen.sh
  hack/update-vendor.sh
  hack/verify-codegen.sh
  hack/verify-style.sh
Labels: approved, lgtm

#868 OTA-844: pkg/cvo/metrics: Add 'reason' to cluster_operator_up
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
Labels: approved, lgtm

#876 OCPBUGS-4986: pkg/payload/precondition: Do not claim warnings would have blocked
  pkg/payload/precondition/precondition.go
  pkg/payload/precondition/precondition_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#877 pkg/payload: code cleanups
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/payload/render.go
  pkg/payload/task.go
  pkg/payload/task_graph_test.go
  pkg/payload/task_test.go
Labels: approved, lgtm

#875 tests: fix rare nil dereference in `TestCache`
  pkg/clusterconditions/cache/cache_test.go
  pkg/clusterconditions/mock/mock.go
  pkg/clusterconditions/mock/mock_test.go
Labels: approved, lgtm

#846 Bug 2090680: pkg/cvo/updatepayload.go: timeout payload retrieval
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
