Repository openshift/cluster-version-operator, pull requests merged in 2022-09, with the labels that each got.

#833 pkg/cvo: add test utility functions
  go.mod
  go.sum
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-openapi/jsonpointer/go.mod
  vendor/github.com/go-openapi/jsonpointer/go.sum
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/jpillora/backoff/go.mod
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/json/go.mod
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: approved, lgtm

#838 OWNERS: Prune vrutkovs
  OWNERS
Labels: approved, lgtm

#836 OCPBUGS-1251: Add admin-gate ack-4.11-kube-1.25-api-removals-in-4.12
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important

#832 OCPBUGS-1402: pkg/cvo/sync_worker.go: remove Lock/Unlock
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/testdata/payloadtest-3/manifests/.gitkeep
  pkg/cvo/testdata/payloadtest-3/release-manifests/0000_10_a_file.yaml
  pkg/cvo/testdata/payloadtest-3/release-manifests/image-references
  pkg/cvo/testdata/payloadtest-3/release-manifests/release-metadata
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#837 Bug 1951835: Handle report only sync errors
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
