Repository openshift/cluster-version-operator, pull requests merged in 2022-10, with the labels that each got.

#840 OCPBUGS-1636: pkg/cvo/sync_worker: Pre-create ClusterOperator in reconciling-mode too
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-important

#844 Fix ups from gofmt 1.19 and yamllint
  bootstrap/bootstrap-pod.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cincinnati/cincinnati.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#849 Fix ups from gofmt 1.19
  pkg/cincinnati/cincinnati.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#845 Dockerfile: Bump to Go 1.18
  Dockerfile
Labels: approved, lgtm

#841 Bug 2033499: Populate acceptedRisks in ClusterVersion History
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/precondition/clusterversion/recommendedupdate.go
  pkg/payload/precondition/clusterversion/recommendedupdate_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#856 OCPBUGS-2727: Do not fail precondition check for UnknownUpdate
  pkg/payload/precondition/clusterversion/recommendedupdate.go
  pkg/payload/precondition/precondition.go
  pkg/payload/precondition/precondition_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#858 resourcemerge: cleanup deprecated function calls
  lib/resourcemerge/apps_test.go
  lib/resourcemerge/batch_test.go
  lib/resourcemerge/core_test.go
  lib/resourcemerge/meta_test.go
  lib/resourcemerge/rbac_test.go
Labels: approved, lgtm
