Repository openshift/cluster-version-operator, pull requests merged in 2022-08, with the labels that each got.

#796 Pull arch from payload
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#810 Revert "Pull arch from payload"
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#577 pkg/cvo/sync_worker: Consolidate all ClusterOperator errors by reason
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
  pkg/cvo/sync_worker_test.go
  pkg/payload/task.go
Labels: approved, do-not-merge/hold, lgtm

#814 pkg/cvo/status.go: sort implicitly enabled caps
  pkg/cvo/status.go
Labels: approved, lgtm

#818 Bug 2117033: pkg/cvo/sync_worker: Trigger new sync round on ClusterOperator versions[name=operator] changes
  pkg/cvo/cvo.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#805 /pkg/cvo: improve CV history pruning
  pkg/cvo/status.go
  pkg/cvo/status_history.go
  pkg/cvo/status_history_test.go
  pkg/cvo/status_test.go
Labels: approved, lgtm

#813 Restore 'Pull arch from payload' and fix
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/cvo_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm

#800 Bug 2010365: OpenShift Alerting Rules Style-Guide Compliance
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#662 Bug 1951835: Propagate Degraded to update status
  pkg/cvo/internal/operatorstatus.go
  pkg/cvo/internal/operatorstatus_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/payload/task.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#827 lib/capability: Sort all slices after building them
  lib/capability/capability.go
Labels: approved, lgtm

#828 OCPBUGS-569: CVO History Pruner return not assigned to config.Status.History
  pkg/cvo/status.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#808 Bug 2006611: Upgrade takes too much time when upgrading via --to-image
  pkg/cvo/cvo.go
  pkg/cvo/upgradeable.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#830 OCPBUGS-575: lib/resourcemerge/core: Reconcile seccompProfile in ensurePodSecurityContext
  lib/resourcemerge/core.go
  lib/resourcemerge/core_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-important
