Repository openshift/cluster-version-operator, pull requests merged in 2023-01, with the labels that each got.

#839 pkg/cincinnati: Set User-Agent for Cincinnati requests
  pkg/cincinnati/cincinnati.go
  pkg/cincinnati/cincinnati_test.go
  pkg/cvo/availableupdates.go
  pkg/cvo/egress.go
Labels: approved, lgtm

#881 Revert "pkg/cvo/updatepayload.go: timeout payload retrieval"
  pkg/cvo/updatepayload.go
Labels: approved, lgtm

#882 OCPBUGS-5505: Set upgradeability check throttling period to 2m
  pkg/cvo/cvo.go
  pkg/cvo/upgradeable.go
  pkg/cvo/upgradeable_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#887 start.go: simplify code for computing sync period
  pkg/start/start.go
Labels: approved, lgtm

#886 upgradeable: improve logging and refactor
  pkg/cvo/upgradeable.go
Labels: approved, lgtm

#891 Adding David to approvers list and removing Jack
  OWNERS
Labels: approved, lgtm

#888 lib/validation: Drop "a previous version" from desiredUpdate validation
  lib/validation/validation.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm

#870 OCPBUGS-702: Fix removing `caBundle` field of CRDs when `...inject-cabundle=true`
  lib/resourceapply/apiext.go
  lib/resourcemerge/apiext.go
  lib/resourcemerge/apiext_test.go
  lib/resourcemerge/helper.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#889 logging: consistently use RFC3339 in log messages
  lib/resourcedelete/helper.go
  pkg/autoupdate/autoupdate.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/payload/precondition/clusterversion/upgradeable.go
Labels: approved, lgtm

#885 [release-4.11] OCPBUGS-5882: Set upgradeability check throttling period to 2m
  pkg/cvo/upgradeable.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
