Repository openshift/cluster-version-operator, pull requests merged in 2023-10, with the labels that each got.

#981 OCPBUGS-20321: pkg/cvo/sync_worker: Always enable the DeploymentConfig capability
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#984 OCPVE-740: vendor: bump openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_openshift-controller-manager-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.build.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#985 OCPBUGS-22198: Reconcile Volumes in SCCs
  lib/resourceapply/security.go
  lib/resourceapply/security_test.go
  lib/resourcemerge/core.go
  lib/resourcemerge/security.go
  lib/resourcemerge/security_test.go
  pkg/cvo/upgradeable.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_securitycontextconstraints.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#961 OCPBUGS-9050: Alert on failing conditional update risk evaluation
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/cvo/availableupdates.go
  pkg/cvo/availableupdates_test.go
  pkg/cvo/metrics.go
  pkg/cvo/metrics_test.go
  pkg/cvo/status.go
Labels: approved, lgtm, tide/merge-method-squash, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
