Repository openshift/cluster-version-operator, pull requests merged in 2023-12, with the labels that each got.

#999 OTA-855: Create GET requests to the Prometheus API server
  pkg/clusterconditions/promql/promql.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#963 OCPVE-646: add cloud credential capability
  go.mod
  go.sum
  lib/capability/capability_test.go
  pkg/cvo/cvo_scenarios_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/custom.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/custom.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.authentication.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.network.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1003 OCPBUGS-25055: pkg/cvo/sync_worker: Verification-failure details for unforced updates too
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#996 OCPBUGS-24535: pkg/payload/precondition/clusterversion/rollback: Allow previous version within z-stream
  pkg/cvo/cvo.go
  pkg/payload/precondition/clusterversion/rollback.go
  pkg/payload/precondition/clusterversion/rollback_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, no-qe
