Repository openshift/cluster-version-operator, pull requests merged in 2023-09, with the labels that each got.

#965 OCPBUGS-18567: lib/resourcemerge/apps: Cover paused and other spec properties in EnsureDeployment
  lib/resourcemerge/apps.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#968 OCPBUGS-18984: pkg/payload/precondition/clusterversion/etcdbackup: Drop precondition
  pkg/cvo/cvo.go
  pkg/payload/precondition/clusterversion/etcdbackup.go
  pkg/payload/precondition/clusterversion/upgradeable.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#964 availableupdates: do not reset lastTransitionTime on unchanged status
  pkg/clusterconditions/mock/mock.go
  pkg/cvo/availableupdates.go
  pkg/cvo/availableupdates_test.go
Labels: approved, lgtm, tide/merge-method-squash, qe-approved

#926 OTA-854: Add configurable CVO knobs for risk-evaluation PromQL target
  cmd/start.go
  pkg/cincinnati/cincinnati_test.go
  pkg/clusterconditions/clusterconditions.go
  pkg/clusterconditions/clusterconditions_test.go
  pkg/clusterconditions/promql/promql.go
  pkg/clusterconditions/standard/standard.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/start/start.go
Labels: approved, lgtm, jira/valid-reference

#966 OCPBUGS-18386: Properly reconcile SCC resources
  lib/resourceapply/security.go
  lib/resourceapply/security_test.go
  lib/resourcemerge/core.go
  lib/resourcemerge/security.go
  lib/resourcemerge/security_test.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_securitycontextconstraints.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#939 OCPBUGS-19512: pkg/clusterconditions/promql: Warm cache with 1s delay
  pkg/clusterconditions/promql/promql.go
  pkg/cvo/availableupdates.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#972 OCPBUGS-19465: Properly reconcile SCC resources
  lib/resourceapply/security.go
  lib/resourceapply/security_test.go
  lib/resourcemerge/core.go
  lib/resourcemerge/security.go
  lib/resourcemerge/security_test.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_securitycontextconstraints.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#973 OCPBUGS-19737: pkg/clusterconditions/promql: Warm cache with 1s delay
  pkg/clusterconditions/mock/mock.go
  pkg/clusterconditions/promql/promql.go
  pkg/cvo/availableupdates.go
  pkg/cvo/availableupdates_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#975 OCPBUGS-19868: pkg/clusterconditions/cache: Avoid panic on all-fresh-cache evaluation
  pkg/clusterconditions/cache/cache.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
