Repository openshift/cluster-version-operator, pull requests merged in 2023-11, with the labels that each got.

#992 OCPBUGS-8079: install/0000_90_cluster-version-operator_02_servicemonitor: Drop $ from ${{
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#988 OCPBUGS-22408: pkg/clusterconditions/promql: Warm cache with 1s delay
  pkg/clusterconditions/cache/cache.go
  pkg/clusterconditions/mock/mock.go
  pkg/clusterconditions/promql/promql.go
  pkg/cvo/availableupdates.go
  pkg/cvo/availableupdates_test.go
  pkg/cvo/cvo_scenarios_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#993 OCPBUGS-19391: do not reconcile rules if aggregationRule is set
  lib/resourcemerge/rbac.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#997 OCPBUGS-23377: to reduce log noise, only log sync_worker messages on retry or payload change
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
