Repository openshift/cluster-version-operator, pull requests merged in 2023-03, with the labels that each got.

#908 OCPBUGS-8304: Adding admin-gate ack-4.12-kube-1.26-api-removals-in-4.13
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#909 OCPBUGS-5469: pkg/cvo/availableupdates: Prioritize conditional risks for largest target version
  pkg/cvo/availableupdates.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#918 OTA-941: pkg/payload/precondition/clusterversion/rollback: New precondition
  pkg/cvo/cvo.go
  pkg/payload/precondition/clusterversion/rollback.go
  pkg/payload/precondition/clusterversion/rollback_test.go
Labels: approved, lgtm, jira/valid-reference
