Repository openshift/cluster-version-operator, pull requests merged in 2023-02, with the labels that each got.

#893 Bug 2089138: CVO hotloops on ValidatingWebhookConfiguration
  hack/generate-lib-resources.py
  lib/resourceapply/admissionregistration.go
  lib/resourcebuilder/resourcebuilder.go
  lib/resourcedelete/admissionregistration.go
  lib/resourcemerge/admissionregistration.go
  lib/resourcemerge/admissionregistration_test.go
  lib/resourceread/resourceread.go
Labels: approved, lgtm, ¯\_(ツ)_/¯, bugzilla/valid-bug, bugzilla/severity-medium

#883 [PSAP-741] vendor: update openshift/api for NodeTuning capability
  go.mod
  go.sum
  lib/capability/capability_test.go
  pkg/cvo/cvo_scenarios_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#898 pkg/cvo/sync_worker: Fix "The sync worker already has a pending notification" formatting
  pkg/cvo/sync_worker.go
Labels: approved, lgtm

#896 Bug 2090680: RetrievePayload: Improve timeouts and cover behavior with tests
  pkg/cvo/updatepayload.go
  pkg/cvo/updatepayload_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#894 OCPBUGS-6097: CVO hotloops on ImageStream and logs the information incorrectly
  lib/resourceapply/imagestream.go
  lib/resourcemerge/imagestream.go
  lib/resourcemerge/imagestream_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#906 install/0000_90_cluster-version-operator_02_servicemonitor: Add ClusterReleaseNotAccepted
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
Labels: approved, lgtm

#904 OCPBUGS-7419: Trigger new sync round on ClusterOperator Available changes
  pkg/cvo/cvo.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
