Repository openshift/cluster-version-operator, pull requests merged in 2024-06, with the labels that each got.

#1049 OCPBUGS-33984: Add admin-gate for OCP 4.16
  install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1052 OCPBUGS-35236: Revert: Add support for Custom Certificate Authorities for custom signature stores"
  pkg/customsignaturestore/customsignaturestore.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/egress.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, no-qe

#1054 NO-JIRA: typo change previousily to previously
  lib/capability/capability.go
  lib/resourcedelete/apiext.go
  lib/resourcedelete/apps.go
  lib/resourcedelete/core.go
  lib/resourcedelete/imagestream.go
  lib/resourcedelete/rbac.go
  lib/resourcedelete/security.go
  pkg/cvo/cvo.go
  pkg/cvo/status.go
Labels: approved, needs-ok-to-test, lgtm, jira/valid-reference, no-qe

#1055 Revert "OCPBUGS-34287: Updating cluster-version-operator-container image to be consistent with ART for 4.17"
  .ci-operator.yaml
  Dockerfile.rhel
  go.mod
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, no-qe

#1058 NO-JIRA: Update OWNERS
  OWNERS
Labels: approved, lgtm, jira/valid-reference, no-qe
