Repository openshift/cluster-version-operator, pull requests merged in 2024-11, with the labels that each got.

#1100 NO-JIRA: task graph: improve TestRunGraph tests
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1097 [release-4.16] OCPBUGS-43964: Fix desired before sync_worker's work is initialized
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1101 NO-JIRA: task graph: test speedup and code cleaup
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1102 OCPBUGS-22442: Fix `TestRunGraph/mid-task_cancellation_with_work_in_queue_does_not_deadlock` flake
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1098 OCPBUGS-44018: pkg/cvo/availableupdates: Preserve update advice on update-service failures
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1104 OCPBUGS-44328: Fix desired before sync_worker's work is initialized
  pkg/cvo/cvo.go
  pkg/cvo/cvo_scenarios_test.go
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1110 MULTIARCH-4559: pkg: Propagate Release.Architecture
  go.mod
  go.sum
  pkg/cincinnati/cincinnati.go
  pkg/cvo/availableupdates.go
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/cvo/updatepayload.go
  pkg/featuregates/featuregates.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
  pkg/start/start_integration_test.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1111 MULTIARCH-4559: pkg/featuregates: Fix statusReleaseArchitecture enablement
  pkg/featuregates/featuregates.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1080 OTA-861: Set Upgradeable=False when there is an upgrade in progress
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/upgradeable.go
  pkg/cvo/upgradeable_test.go
Labels: approved, lgtm, tide/merge-method-squash, qe-approved, jira/valid-reference

#1106 OCPBUGS-31462: Set `openshift.io/required-scc: privileged` annotation in `version` pods
  pkg/cvo/updatepayload.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference
