Repository openshift/cluster-version-operator, pull requests merged in 2024-10, with the labels that each got.

#1090 NO-JIRA: OWNERS: Update the username of David Hurta
  OWNERS
Labels: approved, lgtm, jira/valid-reference, no-qe

#1087 OCPBUGS-41642: vendor: Update openshift/api to pick up the v4.17 capability sets
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_featuregates.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
  vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1094 OCPBUGS-42880: Upgradeable=False should not block a 4.(y+1).z to 4.(y+1).z' retarget
  pkg/cvo/status_history.go
  pkg/cvo/status_history_test.go
  pkg/cvo/upgradeable.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/clusterversion/upgradeable_test.go
Labels: approved, lgtm, tide/merge-method-squash, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1099 NO-JIRA: task graph: comments and cleanups
  pkg/payload/task_graph.go
  pkg/payload/task_graph_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe
