Repository openshift/cluster-version-operator, pull requests merged in 2024-01, with the labels that each got.

#1009 OCPBUGS-25708: pkg/cvo/availableupdates: Only bump LastAttempt on Cincinnati pulls
  pkg/cvo/availableupdates.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#1012 OCPBUGS-26014: clusterOperatorBuilder: Reconcile metadata on COs
  lib/resourcemerge/os.go
  pkg/cvo/internal/operatorstatus.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1011 OCPBUGS-25862: CO health: only track current in-progress upgrade start
  pkg/cvo/internal/operatorstatus.go
  pkg/payload/task.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1020 OCPBUGS-7714: Refactor & improve SyncWorker lock code
  pkg/cvo/sync_test.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, no-qe

#1026 OCPBUGS-27468: bump(openshift/api)=master to pick up new TechPreviewNoUpgrade features
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, no-qe

#1028 OCPBUGS-27822: Revert "[release-4.14] OCPBUGS-27175: clusterOperatorBuilder: Reconcile metadata on COs"
  lib/resourcemerge/os.go
  pkg/cvo/internal/operatorstatus.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1027 NO-JIRA: manifests: fix service manifest filename
  install/0000_00_cluster-version-operator_04_service.yaml
Labels: approved, lgtm, jira/valid-reference, no-qe

#1005 OCPBUGS-7714: yield lock while retrieving payload
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#962 OCPBUGS-18454: Avoid using risk names as condition reasons when invalid
  pkg/cvo/availableupdates.go
  pkg/cvo/availableupdates_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1031 OTA-1159: [1/x] Refactor syncStatus for testability
  pkg/cvo/cvo.go
  pkg/cvo/cvo_test.go
  pkg/cvo/status.go
Labels: approved, lgtm, jira/valid-reference, no-qe
