Repository openshift/cluster-version-operator, pull requests merged in 2025-02, with the labels that each got.

#1138 OTA-1339: USC: Pull latest UpdateStatus API code
  pkg/updatestatus/controlplaneinformer.go
  pkg/updatestatus/controlplaneinformer_test.go
  pkg/updatestatus/nodeinformer.go
  pkg/updatestatus/nodeinformer_test.go
  pkg/updatestatus/types_update_status.go
  pkg/updatestatus/types_update_status_health.go
  pkg/updatestatus/types_update_status_progress.go
  pkg/updatestatus/updatestatuscontroller_test.go
  pkg/updatestatus/zz_generated.deepcopy.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1141 OTA-1418: Allow forcing health insights on CV
  pkg/updatestatus/controlplaneinformer.go
  pkg/updatestatus/controlplaneinformer_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1148 OTA-209: Resolve lint issues
  cmd/start.go
  lib/resourcemerge/batch_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1146 OTA-1418: USC: Make messages more robust and decoupled
  pkg/updatestatus/controlplaneinformer.go
  pkg/updatestatus/controlplaneinformer_test.go
  pkg/updatestatus/nodeinformer.go
  pkg/updatestatus/nodeinformer_test.go
  pkg/updatestatus/updatestatuscontroller.go
  pkg/updatestatus/updatestatuscontroller_test.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1143 OTA-1418: USC: Drop unknown messages from the API
  pkg/updatestatus/updatestatuscontroller.go
  pkg/updatestatus/updatestatuscontroller_test.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1150 OTA-1418: USC: Drop unknown insights after grace period
  pkg/updatestatus/updatestatuscontroller.go
  pkg/updatestatus/updatestatuscontroller_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1156 NO-JIRA: Fix a few AMD64-oriented tests on Non-AMD64 machines
  pkg/cvo/availableupdates_test.go
  pkg/cvo/cvo_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1093 OTA-861: Generate an accepted risk for Y-then-Z upgrade
  pkg/cvo/status_history.go
  pkg/cvo/upgradeable.go
  pkg/payload/precondition/clusterversion/upgradeable.go
  pkg/payload/precondition/clusterversion/upgradeable_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1149 NO-JIRA: Update ClusterOperator Status Conditions to `listType=map`
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusteroperators.crd.yaml
  vendor/github.com/openshift/api/features/features.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, no-qe

#1131 NO-JIRA: Refactor for readability
  lib/capability/capability.go
  lib/capability/capability_test.go
  pkg/cvo/cvo.go
  pkg/cvo/sync_worker.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1145 OTA-1427: Polish reason and message in Node's status insight
  pkg/updatestatus/mco/layered_node_state.go
  pkg/updatestatus/nodeinformer.go
  pkg/updatestatus/nodeinformer_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1157 NO-JIRA: Rename fields in ClusterCapabilities for readability
  lib/capability/capability.go
  lib/capability/capability_test.go
  pkg/cvo/status.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1162 OTA-1418: Decribe informer->usc communication
  pkg/updatestatus/updatestatuscontroller.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1161 OTA-209: Add `ClusterVersionOperator` manifests
  Dockerfile
  Dockerfile.rhel
  install/0000_00_cluster-version-operator_02_configuration-DevPreviewNoUpgrade.yaml
  pkg/dependencymagnet/doc.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversionoperators-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversionoperators-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_config-operator_01_imagecontentsourcepolicies.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_etcd_01_etcdbackups-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_etcd_01_etcdbackups-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_etcd_01_etcdbackups-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/doc.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, no-qe

#1144 OTA-1427: Recompute node insights when MC/MCP changes
  pkg/updatestatus/controlplaneinformer_test.go
  pkg/updatestatus/nodeinformer.go
  pkg/updatestatus/nodeinformer_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe
