Repository openshift/cluster-version-operator, pull requests merged in 2025-05, with the labels that each got.

#1183 NO-JIRA: Makefile: verify -> verify-yaml
  Makefile
Labels: approved, lgtm, jira/valid-reference, no-qe

#1180 OCPBUGS-53062: add the ports Field into the CVO's container spec
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_00_cluster-version-operator_04_service.yaml
  pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#1184 OTA-1531: [1/x] cvo: refactor option processing
  cmd/cluster-version-operator/start.go
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1185 OTA-1531: [2/x] cvo: refactor `LoadUpdate`
  pkg/payload/payload.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1188 OTA-1531: [3/x] cvo: read version from release metadata on startup
  pkg/payload/payload.go
  pkg/start/start.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1133 OTA-1010: Add a new version of GetImplicitlyEnabledCapabilities
  lib/capability/capability.go
  lib/capability/capability_test.go
  lib/manifest/manifest.go
  pkg/payload/payload.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1189 OTA-1531: [4/x] cvo: extract config informer creation
  pkg/start/start.go
  pkg/start/start_integration_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1179 OTA-1403: Update and Verify Test Metadata Using Makefile
  .openshift-tests-extension/openshift_payload_cluster-version-operator.json
  Makefile
  hack/build-go.sh
  hack/build-info.sh
  hack/update-test-metadata.sh
Labels: approved, lgtm, jira/valid-reference, no-qe

#1190 OTA-1531: [5/x] cvo: read cluster `FeatureGate` early
  pkg/featuregates/featuregates.go
  pkg/start/start.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1191 OCPBUGS-56114: Fix ImplicitlyEnabledCapabilities
  pkg/cvo/status.go
  pkg/cvo/status_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference
