Repository openshift/cluster-version-operator, pull requests merged in 2025-03, with the labels that each got.

#1159 NO-JIRA: Use k8s.sets for the fields of ClusterCapabilities
  lib/capability/capability.go
  lib/capability/capability_test.go
  pkg/cvo/sync_worker.go
  pkg/payload/payload.go
  pkg/payload/payload_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1166 OCPBUGS-52258: pkg/cvo/updatepayload: Context around ValidateDirectory calls
  pkg/cvo/updatepayload.go
  pkg/payload/image.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1164 OTA-1427: Reconcile all nodes via a special event
  pkg/updatestatus/nodeinformer.go
  pkg/updatestatus/nodeinformer_test.go
Labels: approved, lgtm, jira/valid-reference, no-qe

#1169 OTA-1403: Move the CVO CLI Application to a Separate Folder
  cmd/cluster-version-operator/image.go
  cmd/cluster-version-operator/main.go
  cmd/cluster-version-operator/render.go
  cmd/cluster-version-operator/start.go
  cmd/cluster-version-operator/updatestatuscontroller.go
  cmd/cluster-version-operator/version.go
  hack/build-go.sh
Labels: approved, lgtm, jira/valid-reference, no-qe

#1173 NO-JIRA: Add unit test for renderManifest
  pkg/payload/render_test.go
  pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe
