Repository openshift/cluster-version-operator, pull requests merged in 2025-04, with the labels that each got.

#1168 OTA-1403: Create minimal openshift tests extension
  cmd/cluster-version-operator-tests/main.go
  go.mod
  go.sum
  hack/build-go.sh
  vendor/github.com/openshift-eng/openshift-tests-extension/LICENSE
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmd.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdimages/cmdimages.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdinfo/info.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdlist/list.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdrun/runsuite.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdrun/runtest.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdupdate/update.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/dbtime/time.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extension.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/environment.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/result.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/result_writer.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/spec.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/task.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/types.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/registry.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/types.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/component.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/concurrency.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/environment.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/names.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/output.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/suite.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/LICENSE
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/README.md
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/byte.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/doc.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/empty.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/int.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/int32.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/int64.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/set.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/string.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, no-qe

#1174 NO-JIRA: Fix some issues identified by yamllint
  install/0000_00_cluster-version-operator_00_namespace.yaml
  install/0000_00_cluster-version-operator_03_deployment.yaml
  install/0000_00_cluster-version-operator_04_service.yaml
  install/0000_00_update-status-controller_00_namespace-DevPreviewNoUpgrade.yaml
  install/0000_00_update-status-controller_03_deployment-DevPreviewNoUpgrade.yaml
  install/0000_90_cluster-version-operator_02_servicemonitor.yaml
  pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml
Labels: approved, lgtm, jira/valid-reference, no-qe

#1175 OTA-1488: Remove DevPreview USC manifests
  hack/test-usc-integration.sh
  install/0000_00_update-status-controller_00_namespace-DevPreviewNoUpgrade.yaml
  install/0000_00_update-status-controller_01_serviceaccount-DevPreviewNoUpgrade.yaml
  install/0000_00_update-status-controller_02_rbac-DevPreviewNoUpgrade.yaml
  install/0000_00_update-status-controller_03_deployment-DevPreviewNoUpgrade.yaml
Labels: approved, lgtm, jira/valid-reference, no-qe

#1171 NO-JIRA: manifests: make template manifests valid YAML
  install/0000_00_cluster-version-operator_03_deployment.yaml
  pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml
Labels: approved, lgtm, jira/valid-reference, no-qe

#1165 OCPBUGS-23514: Failing=Unknown upon long CO updating
  pkg/cvo/status.go
  pkg/cvo/status_test.go
  pkg/payload/task.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1177 NO-JIRA: make verify
  Makefile
  bootstrap/bootstrap-pod.yaml
  hack/verify-style.sh
  hack/verify-yaml.sh
  hack/yamllint-config.yaml
Labels: approved, lgtm, jira/valid-reference, no-qe
